import 'package:flutter/material.dart';

/// Localized content for all doctors in all supported languages
class DoctorLocalizedContent {
  static Map<String, dynamic> getContent(String doctorId, String locale) {
    final allContent = _getAllDoctorsContent();
    return allContent[doctorId]?[locale] ?? allContent[doctorId]?['tr'] ?? {};
  }

  static Map<String, Map<String, Map<String, dynamic>>> _getAllDoctorsContent() {
    return {
      'dr_gokay_bilgin': {
        'tr': {
          'biography': 'Dr. Gökay Bilgin, Smile Hair Clinic\'in kurucu ortağıdır. Kariyerinin ilk yıllarına Medical Park Sağlık Grubu\'nda başladı. Medicana Sağlık Grubunda Başhekim Yardımcılığına atandı ve Smile Hair Clinic\'in kurucu ortağı oldu. 4000\'den fazla saç ekimi işlemini tamamladı.',
          'title': 'Saç Ekimi Cerrahı, M.D.',
          'specialization': 'Medikal Estetik Hekimi',
          'expertise': ['Mikromotor Greft Ekstraksiyonu', 'Safir FUE Saç Ekimi', 'TrueTM Philosophy'],
          'interview': {
            'Temel değerleriniz nelerdir?': 'Hem iş hayatımda hem de özel hayatımda öğrenme kültürüne önem veririm. İş yerinde ilerlemek, gelişmek ve asla durmamak benim için çok önemli.',
            'Klinikte çalışma tarzınız nasıldır?': 'Yaptığınız işten keyif alırsanız başarılı ve tatmin olacağınıza inanıyorum. Tüm dönüşüm sürecini, bir erkeğin nasıl True Gentlemen\'a dönüştüğünü gözlemlemekten keyif alıyorum.',
            'Burcunuz Nedir?': 'Kova',
            'Favori Parfümünüz Hangisidir?': 'Louis Vuitton – Au Hasard. Ahşap karakteri dünyaya bağlı olduğumu hissettiriyor.',
            'Başucu kitabınız nedir?': 'Yüzüklerin Efendisi Serisi. Fantastik evreninde kaybolmayı seviyorum.',
            'İlham verici şehirler': 'Berlin, Paris ve Amsterdam. Batı Avrupa kültürünün gerçek bir hayranıyım.',
          },
        },
        'en': {
          'biography': 'Dr. Gökay Bilgin is a co-founder of Smile Hair Clinic. He started his career at Medical Park Health Group. He was appointed as Assistant Chief Physician at Medicana Health Group and became a co-founder of Smile Hair Clinic. He has completed over 4000 hair transplant procedures.',
          'title': 'Hair Transplant Surgeon, M.D.',
          'specialization': 'Medical Aesthetic Physician',
          'expertise': ['Micromotor Graft Extraction', 'Sapphire FUE Hair Transplant', 'TrueTM Philosophy'],
          'interview': {
            'What are your core values?': 'I value learning culture both in my professional and personal life. Progressing, developing and never stopping at work is very important to me.',
            'How do you work at the clinic?': 'I believe that if you enjoy what you do, you will be successful and satisfied. I enjoy observing the entire transformation process, how a man transforms into a True Gentleman.',
            'What is your zodiac sign?': 'Aquarius',
            'What is your favorite perfume?': 'Louis Vuitton – Au Hasard. The woody character makes me feel connected to the world.',
            'What is your bedside book?': 'The Lord of the Rings Series. I love getting lost in the fantasy universe.',
            'Inspiring cities': 'Berlin, Paris and Amsterdam. I am a true fan of Western European culture.',
          },
        },
        'ar': {
          'biography': 'الدكتور جوكاي بيلجين هو الشريك المؤسس لعيادة سمايل هير. بدأ مسيرته المهنية في مجموعة ميديكال بارك الصحية. تم تعيينه كمساعد رئيس الأطباء في مجموعة ميديكانا الصحية وأصبح شريكًا مؤسسًا لعيادة سمايل هير. أكمل أكثر من 4000 عملية زراعة شعر.',
          'title': 'جراح زراعة الشعر، دكتور في الطب',
          'specialization': 'طبيب التجميل الطبي',
          'expertise': ['استخراج الطعم الدقيق بالميكروموتور', 'زراعة الشعر FUE بالياقوت', 'فلسفة TrueTM'],
          'interview': {
            'ما هي قيمك الأساسية؟': 'أقدر ثقافة التعلم في حياتي المهنية والشخصية. التقدم والتطوير وعدم التوقف في العمل مهم جدًا بالنسبة لي.',
            'كيف تعمل في العيادة؟': 'أعتقد أنه إذا استمتعت بما تفعله، فستكون ناجحًا ومرضيًا. أستمتع بمراقبة عملية التحول الكاملة، كيف يتحول الرجل إلى رجل نبيل حقيقي.',
            'ما هو برجك؟': 'الدلو',
            'ما هو عطرك المفضل؟': 'لويس فويتون - Au Hasard. الطابع الخشبي يجعلني أشعر بالاتصال بالعالم.',
            'ما هو كتابك المفضل؟': 'سلسلة سيد الخواتم. أحب أن أضيع في الكون الخيالي.',
            'المدن الملهمة': 'برلين وباريس وأمستردام. أنا معجب حقيقي بالثقافة الأوروبية الغربية.',
          },
        },
        'de': {
          'biography': 'Dr. Gökay Bilgin ist Mitbegründer der Smile Hair Clinic. Er begann seine Karriere bei der Medical Park Health Group. Er wurde zum stellvertretenden Chefarzt der Medicana Health Group ernannt und wurde Mitbegründer der Smile Hair Clinic. Er hat über 4000 Haartransplantationsverfahren abgeschlossen.',
          'title': 'Haartransplantationschirurg, M.D.',
          'specialization': 'Medizinischer Ästhetiker',
          'expertise': ['Mikromotor-Graft-Extraktion', 'Saphir FUE Haartransplantation', 'TrueTM Philosophie'],
          'interview': {
            'Was sind Ihre Grundwerte?': 'Ich schätze die Lernkultur sowohl in meinem Berufs- als auch in meinem Privatleben. Fortschritt, Entwicklung und niemals aufzuhören bei der Arbeit ist für mich sehr wichtig.',
            'Wie arbeiten Sie in der Klinik?': 'Ich glaube, dass man erfolgreich und zufrieden sein wird, wenn man Spaß an dem hat, was man tut. Ich beobachte gerne den gesamten Transformationsprozess, wie sich ein Mann in einen wahren Gentleman verwandelt.',
            'Was ist Ihr Sternzeichen?': 'Wassermann',
            'Was ist Ihr Lieblingsparfüm?': 'Louis Vuitton – Au Hasard. Der holzige Charakter lässt mich mich mit der Welt verbunden fühlen.',
            'Was ist Ihr Lieblingsbuch?': 'Die Herr der Ringe Serie. Ich liebe es, mich im Fantasy-Universum zu verlieren.',
            'Inspirierende Städte': 'Berlin, Paris und Amsterdam. Ich bin ein echter Fan der westeuropäischen Kultur.',
          },
        },
        'es': {
          'biography': 'El Dr. Gökay Bilgin es cofundador de Smile Hair Clinic. Comenzó su carrera en Medical Park Health Group. Fue nombrado Médico Jefe Adjunto en Medicana Health Group y se convirtió en cofundador de Smile Hair Clinic. Ha completado más de 4000 procedimientos de trasplante de cabello.',
          'title': 'Cirujano de Trasplante de Cabello, M.D.',
          'specialization': 'Médico Estético',
          'expertise': ['Extracción de Injertos con Micromotor', 'Trasplante de Cabello FUE con Zafiro', 'Filosofía TrueTM'],
          'interview': {
            '¿Cuáles son sus valores fundamentales?': 'Valoro la cultura del aprendizaje tanto en mi vida profesional como personal. Progresar, desarrollarse y nunca detenerse en el trabajo es muy importante para mí.',
            '¿Cómo trabaja en la clínica?': 'Creo que si disfrutas lo que haces, serás exitoso y satisfecho. Disfruto observando todo el proceso de transformación, cómo un hombre se transforma en un verdadero caballero.',
            '¿Cuál es su signo zodiacal?': 'Acuario',
            '¿Cuál es su perfume favorito?': 'Louis Vuitton – Au Hasard. El carácter leñoso me hace sentir conectado con el mundo.',
            '¿Cuál es su libro de cabecera?': 'La serie El Señor de los Anillos. Me encanta perderme en el universo de fantasía.',
            'Ciudades inspiradoras': 'Berlín, París y Ámsterdam. Soy un verdadero fanático de la cultura de Europa Occidental.',
          },
        },
        'fr': {
          'biography': 'Le Dr Gökay Bilgin est cofondateur de Smile Hair Clinic. Il a commencé sa carrière au Medical Park Health Group. Il a été nommé médecin-chef adjoint au Medicana Health Group et est devenu cofondateur de Smile Hair Clinic. Il a effectué plus de 4000 greffes de cheveux.',
          'title': 'Chirurgien de greffe de cheveux, M.D.',
          'specialization': 'Médecin esthétique',
          'expertise': ['Extraction de greffons par micromoteur', 'Greffe de cheveux FUE Saphir', 'Philosophie TrueTM'],
          'interview': {
            'Quelles sont vos valeurs fondamentales?': 'Je valorise la culture d\'apprentissage dans ma vie professionnelle et personnelle. Progresser, se développer et ne jamais s\'arrêter au travail est très important pour moi.',
            'Comment travaillez-vous à la clinique?': 'Je crois que si vous aimez ce que vous faites, vous serez réussi et satisfait. J\'aime observer tout le processus de transformation, comment un homme se transforme en vrai gentleman.',
            'Quel est votre signe zodiacal?': 'Verseau',
            'Quel est votre parfum préféré?': 'Louis Vuitton – Au Hasard. Le caractère boisé me fait sentir connecté au monde.',
            'Quel est votre livre de chevet?': 'La série Le Seigneur des Anneaux. J\'adore me perdre dans l\'univers fantastique.',
            'Villes inspirantes': 'Berlin, Paris et Amsterdam. Je suis un vrai fan de la culture d\'Europe occidentale.',
          },
        },
        'it': {
          'biography': 'Il Dott. Gökay Bilgin è co-fondatore di Smile Hair Clinic. Ha iniziato la sua carriera presso Medical Park Health Group. È stato nominato Vice Primario presso Medicana Health Group ed è diventato co-fondatore di Smile Hair Clinic. Ha completato oltre 4000 procedure di trapianto di capelli.',
          'title': 'Chirurgo del trapianto di capelli, M.D.',
          'specialization': 'Medico estetico',
          'expertise': ['Estrazione di innesti con micromotore', 'Trapianto di capelli FUE Zaffiro', 'Filosofia TrueTM'],
          'interview': {
            'Quali sono i tuoi valori fondamentali?': 'Apprezzo la cultura dell\'apprendimento sia nella mia vita professionale che personale. Progredire, svilupparsi e non fermarsi mai al lavoro è molto importante per me.',
            'Come lavori in clinica?': 'Credo che se ti piace quello che fai, avrai successo e sarai soddisfatto. Mi piace osservare l\'intero processo di trasformazione, come un uomo si trasforma in un vero gentiluomo.',
            'Qual è il tuo segno zodiacale?': 'Acquario',
            'Qual è il tuo profumo preferito?': 'Louis Vuitton – Au Hasard. Il carattere legnoso mi fa sentire connesso al mondo.',
            'Qual è il tuo libro preferito?': 'La serie Il Signore degli Anelli. Adoro perdermi nell\'universo fantasy.',
            'Città ispiratrici': 'Berlino, Parigi e Amsterdam. Sono un vero fan della cultura dell\'Europa occidentale.',
          },
        },
        'pt': {
          'biography': 'Dr. Gökay Bilgin é cofundador da Smile Hair Clinic. Ele começou sua carreira no Medical Park Health Group. Foi nomeado Médico Chefe Adjunto no Medicana Health Group e tornou-se cofundador da Smile Hair Clinic. Ele completou mais de 4000 procedimentos de transplante de cabelo.',
          'title': 'Cirurgião de Transplante de Cabelo, M.D.',
          'specialization': 'Médico Estético',
          'expertise': ['Extração de Enxertos com Micromotor', 'Transplante de Cabelo FUE Safira', 'Filosofia TrueTM'],
          'interview': {
            'Quais são seus valores fundamentais?': 'Valorizo a cultura de aprendizado tanto na minha vida profissional quanto pessoal. Progredir, desenvolver e nunca parar no trabalho é muito importante para mim.',
            'Como você trabalha na clínica?': 'Acredito que se você gosta do que faz, será bem-sucedido e satisfeito. Gosto de observar todo o processo de transformação, como um homem se transforma em um verdadeiro cavalheiro.',
            'Qual é seu signo?': 'Aquário',
            'Qual é seu perfume favorito?': 'Louis Vuitton – Au Hasard. O caráter amadeirado me faz sentir conectado ao mundo.',
            'Qual é seu livro de cabeceira?': 'A série O Senhor dos Anéis. Adoro me perder no universo de fantasia.',
            'Cidades inspiradoras': 'Berlim, Paris e Amsterdã. Sou um verdadeiro fã da cultura da Europa Ocidental.',
          },
        },
        'ru': {
          'biography': 'Доктор Гёкай Билгин является соучредителем клиники Smile Hair. Он начал свою карьеру в медицинской группе Medical Park. Он был назначен заместителем главного врача в медицинской группе Medicana и стал соучредителем клиники Smile Hair. Он выполнил более 4000 процедур пересадки волос.',
          'title': 'Хирург по пересадке волос, доктор медицины',
          'specialization': 'Врач-эстетик',
          'expertise': ['Экстракция графтов микромотором', 'Пересадка волос FUE сапфиром', 'Философия TrueTM'],
          'interview': {
            'Каковы ваши основные ценности?': 'Я ценю культуру обучения как в профессиональной, так и в личной жизни. Прогресс, развитие и никогда не останавливаться в работе очень важно для меня.',
            'Как вы работаете в клинике?': 'Я верю, что если вам нравится то, что вы делаете, вы будете успешны и довольны. Мне нравится наблюдать за всем процессом трансформации, как мужчина превращается в истинного джентльмена.',
            'Какой у вас знак зодиака?': 'Водолей',
            'Какой у вас любимый парфюм?': 'Louis Vuitton – Au Hasard. Древесный характер заставляет меня чувствовать связь с миром.',
            'Какая ваша любимая книга?': 'Серия Властелин колец. Я люблю теряться в фантастической вселенной.',
            'Вдохновляющие города': 'Берлин, Париж и Амстердам. Я настоящий поклонник западноевропейской культуры.',
          },
        },
        'he': {
          'biography': 'ד"ר גוקאי בילגין הוא מייסד שותף של מרפאת סמייל היר. הוא החל את הקריירה שלו בקבוצת הבריאות מדיקל פארק. הוא מונה לסגן מנהל רפואי בקבוצת הבריאות מדיקנה והפך למייסד שותף של מרפאת סמייל היר. הוא השלים יותר מ-4000 הליכי השתלת שיער.',
          'title': 'מנתח השתלת שיער, ד"ר',
          'specialization': 'רופא אסתטי',
          'expertise': ['חילוץ שתלים במיקרו-מוטור', 'השתלת שיער FUE ספיר', 'פילוסופיה TrueTM'],
          'interview': {
            'מהם הערכים הבסיסיים שלך?': 'אני מעריך את תרבות הלמידה גם בחיי המקצועיים וגם האישיים. התקדמות, פיתוח ולעולם לא לעצור בעבודה חשוב מאוד עבורי.',
            'איך אתה עובד במרפאה?': 'אני מאמין שאם אתה נהנה ממה שאתה עושה, תהיה מצליח ומרוצה. אני נהנה לצפות בכל תהליך השינוי, איך גבר הופך לג\'נטלמן אמיתי.',
            'מה המזל שלך?': 'דלי',
            'מה הבושם האהוב עליך?': 'לואי ויטון – Au Hasard. האופי העץ גורם לי להרגיש מחובר לעולם.',
            'מה הספר האהוב עליך?': 'סדרת שר הטבעות. אני אוהב ללכת לאיבוד ביקום הפנטזיה.',
            'ערים מעוררות השראה': 'ברלין, פריז ואמסטרדם. אני מעריץ אמיתי של התרבות המערב-אירופית.',
          },
        },
        'sq': {
          'biography': 'Dr. Gökay Bilgin është bashkëthemelues i Smile Hair Clinic. Ai filloi karrierën e tij në Medical Park Health Group. Ai u emërua Mjek Kryesor Zëvendës në Medicana Health Group dhe u bë bashkëthemelues i Smile Hair Clinic. Ai ka përfunduar mbi 4000 procedura të transplantimit të flokëve.',
          'title': 'Kirurg i Transplantimit të Flokëve, M.D.',
          'specialization': 'Mjek Estetik',
          'expertise': ['Ekstraktimi i Graftave me Mikromotor', 'Transplantimi i Flokëve FUE Safir', 'Filozofia TrueTM'],
          'interview': {
            'Cilat janë vlerat tuaja themelore?': 'Vlerësoj kulturën e të mësuarit si në jetën time profesionale ashtu edhe personale. Progresimi, zhvillimi dhe mos ndalimi kurrë në punë është shumë i rëndësishëm për mua.',
            'Si punoni në klinikë?': 'Besoj se nëse ju pëlqen ajo që bëni, do të jeni i suksesshëm dhe i kënaqur. Më pëlqen të vëzhgoj të gjithë procesin e transformimit, si një burrë shndërrohet në një Zotëri të vërtetë.',
            'Cili është shenja juaj zodiakale?': 'Ujori',
            'Cili është parfumi juaj i preferuar?': 'Louis Vuitton – Au Hasard. Karakteri druri më bën të ndihem i lidhur me botën.',
            'Cili është libri juaj i preferuar?': 'Seria Zoti i Unazave. Më pëlqen të humbas në universin fantastik.',
            'Qytete frymëzuese': 'Berlin, Paris dhe Amsterdam. Jam një adhurues i vërtetë i kulturës perëndimore evropiane.',
          },
        },
      },
      'dr_mehmet_erdogan': {
        'tr': {
          'biography': 'Dr. Mehmet Erdoğan, Smile Hair Clinic\'in kurucu ortağıdır. Acıbadem Sağlık Grubu\'nda tıp doktoru olarak kariyerine başladı. Medicana Sağlık Grubunda Başhekim Yardımcısı ve Uluslararası Hasta Merkezi Direktörü olarak görev yaptı. 4000\'den fazla operasyon gerçekleştirdi.',
          'title': 'Saç Ekimi Cerrahı, M.D.',
          'specialization': 'Medikal Estetik Hekimi',
          'expertise': ['Micromotor Greft', 'Sapphire FUE', 'Donör Bölge Planlaması', 'Saç Çizgisi Tasarımı'],
          'interview': {
            'Temel değerleriniz nelerdir?': 'Hayatın hemen her alanında estetiğe ve mükemmelliğe değer veririm. Sanatsal yaratıcılığımızı yönlendirdiğine inanıyorum.',
            'Klinikte çalışma tarzınız nasıldır?': 'Her gün yaptığım işten zevk alıyorum, bu benim tutkum. Tekniklerimizi geliştirmek ve yenilikleri tanıtmak için elimden gelenin en iyisini yapıyorum.',
            'Burcunuz Nedir?': 'Yengeç',
            'Favori Parfümünüz Hangisidir?': 'Aventus of Creed. Sofistike bir karışım ve iyi yaşanmış bir hayatın tadını ifade ediyor.',
            'Başucu kitabınız nedir?': 'Temel, Marcus Aurelius.',
            'İlham verici şehirler': 'Havana (Küba), Siam Reap (Kamboçya), Hanoi (Vietnam). El değmemiş kültürler benim için daha büyüleyici.',
          },
        },
        'en': {
          'biography': 'Dr. Mehmet Erdoğan is a co-founder of Smile Hair Clinic. He started his career as a medical doctor at Acıbadem Health Group. He served as Assistant Chief Physician and International Patient Center Director at Medicana Health Group. He has performed over 4000 operations.',
          'title': 'Hair Transplant Surgeon, M.D.',
          'specialization': 'Medical Aesthetic Physician',
          'expertise': ['Micromotor Graft', 'Sapphire FUE', 'Donor Area Planning', 'Hairline Design'],
          'interview': {
            'What are your core values?': 'I value aesthetics and excellence in almost every aspect of life. I believe it guides our artistic creativity.',
            'How do you work at the clinic?': 'I enjoy what I do every day, this is my passion. I do my best to improve our techniques and introduce innovations.',
            'What is your zodiac sign?': 'Cancer',
            'What is your favorite perfume?': 'Aventus of Creed. A sophisticated blend that expresses the taste of a well-lived life.',
            'What is your bedside book?': 'Meditations, Marcus Aurelius.',
            'Inspiring cities': 'Havana (Cuba), Siem Reap (Cambodia), Hanoi (Vietnam). Untouched cultures are more fascinating to me.',
          },
        },
        'ar': {
          'biography': 'الدكتور محمد أردوغان هو الشريك المؤسس لعيادة سمايل هير. بدأ مسيرته المهنية كطبيب في مجموعة أكيبادم الصحية. شغل منصب مساعد رئيس الأطباء ومدير مركز المرضى الدولي في مجموعة ميديكانا الصحية. أجرى أكثر من 4000 عملية.',
          'title': 'جراح زراعة الشعر، دكتور في الطب',
          'specialization': 'طبيب التجميل الطبي',
          'expertise': ['طعم الميكروموتور', 'زراعة الشعر FUE بالياقوت', 'تخطيط منطقة المتبرع', 'تصميم خط الشعر'],
          'interview': {
            'ما هي قيمك الأساسية؟': 'أقدر الجمالية والتميز في كل جانب من جوانب الحياة تقريبًا. أعتقد أنه يوجه إبداعنا الفني.',
            'كيف تعمل في العيادة؟': 'أستمتع بما أفعله كل يوم، هذا شغفي. أبذل قصارى جهدي لتحسين تقنياتنا وإدخال الابتكارات.',
            'ما هو برجك؟': 'السرطان',
            'ما هو عطرك المفضل؟': 'Aventus of Creed. مزيج متطور يعبر عن مذاق حياة معيشة جيدًا.',
            'ما هو كتابك المفضل؟': 'تأملات، ماركوس أوريليوس.',
            'المدن الملهمة': 'هافانا (كوبا)، سيم ريب (كمبوديا)، هانوي (فيتنام). الثقافات التي لم تمس أكثر إثارة بالنسبة لي.',
          },
        },
        'de': {
          'biography': 'Dr. Mehmet Erdoğan ist Mitbegründer der Smile Hair Clinic. Er begann seine Karriere als Arzt bei der Acıbadem Health Group. Er diente als stellvertretender Chefarzt und Direktor des Internationalen Patientencenters bei der Medicana Health Group. Er hat über 4000 Operationen durchgeführt.',
          'title': 'Haartransplantationschirurg, M.D.',
          'specialization': 'Medizinischer Ästhetiker',
          'expertise': ['Mikromotor-Graft', 'Saphir FUE', 'Spenderbereich-Planung', 'Haaransatz-Design'],
          'interview': {
            'Was sind Ihre Grundwerte?': 'Ich schätze Ästhetik und Exzellenz in fast jedem Aspekt des Lebens. Ich glaube, es leitet unsere künstlerische Kreativität.',
            'Wie arbeiten Sie in der Klinik?': 'Ich genieße, was ich jeden Tag tue, das ist meine Leidenschaft. Ich tue mein Bestes, um unsere Techniken zu verbessern und Innovationen einzuführen.',
            'Was ist Ihr Sternzeichen?': 'Krebs',
            'Was ist Ihr Lieblingsparfüm?': 'Aventus of Creed. Eine raffinierte Mischung, die den Geschmack eines gut gelebten Lebens ausdrückt.',
            'Was ist Ihr Lieblingsbuch?': 'Meditationen, Marcus Aurelius.',
            'Inspirierende Städte': 'Havanna (Kuba), Siem Reap (Kambodscha), Hanoi (Vietnam). Unberührte Kulturen sind für mich faszinierender.',
          },
        },
        'es': {
          'biography': 'El Dr. Mehmet Erdoğan es cofundador de Smile Hair Clinic. Comenzó su carrera como médico en Acıbadem Health Group. Se desempeñó como Médico Jefe Adjunto y Director del Centro de Pacientes Internacionales en Medicana Health Group. Ha realizado más de 4000 operaciones.',
          'title': 'Cirujano de Trasplante de Cabello, M.D.',
          'specialization': 'Médico Estético',
          'expertise': ['Injerto Micromotor', 'Trasplante de Cabello FUE con Zafiro', 'Planificación del Área Donante', 'Diseño de Línea de Cabello'],
          'interview': {
            '¿Cuáles son sus valores fundamentales?': 'Valoro la estética y la excelencia en casi todos los aspectos de la vida. Creo que guía nuestra creatividad artística.',
            '¿Cómo trabaja en la clínica?': 'Disfruto lo que hago todos los días, esta es mi pasión. Hago todo lo posible para mejorar nuestras técnicas e introducir innovaciones.',
            '¿Cuál es su signo zodiacal?': 'Cáncer',
            '¿Cuál es su perfume favorito?': 'Aventus of Creed. Una mezcla sofisticada que expresa el sabor de una vida bien vivida.',
            '¿Cuál es su libro de cabecera?': 'Meditaciones, Marco Aurelio.',
            'Ciudades inspiradoras': 'La Habana (Cuba), Siem Reap (Camboya), Hanoi (Vietnam). Las culturas intactas son más fascinantes para mí.',
          },
        },
        'fr': {
          'biography': 'Le Dr Mehmet Erdoğan est cofondateur de Smile Hair Clinic. Il a commencé sa carrière comme médecin au Acıbadem Health Group. Il a servi comme médecin-chef adjoint et directeur du Centre des patients internationaux au Medicana Health Group. Il a effectué plus de 4000 opérations.',
          'title': 'Chirurgien de greffe de cheveux, M.D.',
          'specialization': 'Médecin esthétique',
          'expertise': ['Greffon micromoteur', 'Greffe de cheveux FUE Saphir', 'Planification de la zone donneuse', 'Conception de la ligne de cheveux'],
          'interview': {
            'Quelles sont vos valeurs fondamentales?': 'Je valorise l\'esthétique et l\'excellence dans presque tous les aspects de la vie. Je crois que cela guide notre créativité artistique.',
            'Comment travaillez-vous à la clinique?': 'J\'aime ce que je fais tous les jours, c\'est ma passion. Je fais de mon mieux pour améliorer nos techniques et introduire des innovations.',
            'Quel est votre signe zodiacal?': 'Cancer',
            'Quel est votre parfum préféré?': 'Aventus of Creed. Un mélange sophistiqué qui exprime le goût d\'une vie bien vécue.',
            'Quel est votre livre de chevet?': 'Méditations, Marc Aurèle.',
            'Villes inspirantes': 'La Havane (Cuba), Siem Reap (Cambodge), Hanoï (Vietnam). Les cultures intactes sont plus fascinantes pour moi.',
          },
        },
        'it': {
          'biography': 'Il Dott. Mehmet Erdoğan è co-fondatore di Smile Hair Clinic. Ha iniziato la sua carriera come medico presso Acıbadem Health Group. Ha servito come Vice Primario e Direttore del Centro Pazienti Internazionali presso Medicana Health Group. Ha eseguito oltre 4000 operazioni.',
          'title': 'Chirurgo del trapianto di capelli, M.D.',
          'specialization': 'Medico estetico',
          'expertise': ['Innesto micromotore', 'Trapianto di capelli FUE Zaffiro', 'Pianificazione dell\'area donatrice', 'Progettazione della linea dei capelli'],
          'interview': {
            'Quali sono i tuoi valori fondamentali?': 'Apprezzo l\'estetica e l\'eccellenza in quasi tutti gli aspetti della vita. Credo che guidi la nostra creatività artistica.',
            'Come lavori in clinica?': 'Mi piace quello che faccio ogni giorno, questa è la mia passione. Faccio del mio meglio per migliorare le nostre tecniche e introdurre innovazioni.',
            'Qual è il tuo segno zodiacale?': 'Cancro',
            'Qual è il tuo profumo preferito?': 'Aventus of Creed. Una miscela sofisticata che esprime il gusto di una vita ben vissuta.',
            'Qual è il tuo libro preferito?': 'Meditazioni, Marco Aurelio.',
            'Città ispiratrici': 'L\'Avana (Cuba), Siem Reap (Cambogia), Hanoi (Vietnam). Le culture intatte sono più affascinanti per me.',
          },
        },
        'pt': {
          'biography': 'Dr. Mehmet Erdoğan é cofundador da Smile Hair Clinic. Ele começou sua carreira como médico no Acıbadem Health Group. Serviu como Médico Chefe Adjunto e Diretor do Centro de Pacientes Internacionais no Medicana Health Group. Ele realizou mais de 4000 operações.',
          'title': 'Cirurgião de Transplante de Cabelo, M.D.',
          'specialization': 'Médico Estético',
          'expertise': ['Enxerto Micromotor', 'Transplante de Cabelo FUE Safira', 'Planejamento da Área Doadora', 'Design da Linha do Cabelo'],
          'interview': {
            'Quais são seus valores fundamentais?': 'Valorizo a estética e a excelência em quase todos os aspectos da vida. Acredito que isso guia nossa criatividade artística.',
            'Como você trabalha na clínica?': 'Gosto do que faço todos os dias, esta é minha paixão. Faço o meu melhor para melhorar nossas técnicas e introduzir inovações.',
            'Qual é seu signo?': 'Câncer',
            'Qual é seu perfume favorito?': 'Aventus of Creed. Uma mistura sofisticada que expressa o sabor de uma vida bem vivida.',
            'Qual é seu livro de cabeceira?': 'Meditações, Marco Aurélio.',
            'Cidades inspiradoras': 'Havana (Cuba), Siem Reap (Camboja), Hanói (Vietnã). Culturas intocadas são mais fascinantes para mim.',
          },
        },
        'ru': {
          'biography': 'Доктор Мехмет Эрдоган является соучредителем клиники Smile Hair. Он начал свою карьеру врачом в группе здравоохранения Acıbadem. Он служил заместителем главного врача и директором Международного центра пациентов в группе здравоохранения Medicana. Он выполнил более 4000 операций.',
          'title': 'Хирург по пересадке волос, доктор медицины',
          'specialization': 'Врач-эстетик',
          'expertise': ['Графт микромотор', 'Пересадка волос FUE сапфиром', 'Планирование области донора', 'Дизайн линии волос'],
          'interview': {
            'Каковы ваши основные ценности?': 'Я ценю эстетику и совершенство почти во всех аспектах жизни. Я верю, что это направляет нашу художественную креативность.',
            'Как вы работаете в клинике?': 'Мне нравится то, что я делаю каждый день, это моя страсть. Я делаю все возможное, чтобы улучшить наши техники и внедрить инновации.',
            'Какой у вас знак зодиака?': 'Рак',
            'Какой у вас любимый парфюм?': 'Aventus of Creed. Утонченная смесь, выражающая вкус хорошо прожитой жизни.',
            'Какая ваша любимая книга?': 'Размышления, Марк Аврелий.',
            'Вдохновляющие города': 'Гавана (Куба), Сием Рип (Камбоджа), Ханой (Вьетнам). Нетронутые культуры более увлекательны для меня.',
          },
        },
        'he': {
          'biography': 'ד"ר מהמט ארדואן הוא מייסד שותף של מרפאת סמייל היר. הוא החל את הקריירה שלו כרופא בקבוצת הבריאות אצ\'יבאדם. הוא שירת כסגן מנהל רפואי ומנהל מרכז החולים הבינלאומי בקבוצת הבריאות מדיקנה. הוא ביצע יותר מ-4000 ניתוחים.',
          'title': 'מנתח השתלת שיער, ד"ר',
          'specialization': 'רופא אסתטי',
          'expertise': ['שתל מיקרו-מוטור', 'השתלת שיער FUE ספיר', 'תכנון אזור התורם', 'עיצוב קו השיער'],
          'interview': {
            'מהם הערכים הבסיסיים שלך?': 'אני מעריך אסתטיקה ומצוינות כמעט בכל היבט של החיים. אני מאמין שזה מנחה את היצירתיות האמנותית שלנו.',
            'איך אתה עובד במרפאה?': 'אני נהנה ממה שאני עושה כל יום, זו התשוקה שלי. אני עושה כמיטב יכולתי כדי לשפר את הטכניקות שלנו ולהכניס חידושים.',
            'מה המזל שלך?': 'סרטן',
            'מה הבושם האהוב עליך?': 'Aventus of Creed. תערובת מתוחכמת המבטאת את הטעם של חיים שחיו היטב.',
            'מה הספר האהוב עליך?': 'הרהורים, מרקוס אורליוס.',
            'ערים מעוררות השראה': 'הוואנה (קובה), סיאם ריפ (קמבודיה), האנוי (וייטנאם). תרבויות שלא נגעו בהן מרתקות יותר עבורי.',
          },
        },
        'sq': {
          'biography': 'Dr. Mehmet Erdoğan është bashkëthemelues i Smile Hair Clinic. Ai filloi karrierën e tij si mjek në Acıbadem Health Group. Ai shërbeu si Mjek Kryesor Zëvendës dhe Drejtor i Qendrës së Pacientëve Ndërkombëtare në Medicana Health Group. Ai ka kryer mbi 4000 operacione.',
          'title': 'Kirurg i Transplantimit të Flokëve, M.D.',
          'specialization': 'Mjek Estetik',
          'expertise': ['Graft Mikromotor', 'Transplantimi i Flokëve FUE Safir', 'Planifikimi i Zonës së Dhuruesit', 'Dizajni i Vijës së Flokëve'],
          'interview': {
            'Cilat janë vlerat tuaja themelore?': 'Vlerësoj estetikën dhe përsosmërinë në pothuajse çdo aspekt të jetës. Besoj se udhëheq krijimtarinë tonë artistike.',
            'Si punoni në klinikë?': 'Më pëlqen ajo që bëj çdo ditë, kjo është pasioni im. Bëj më të mirën për të përmirësuar teknikat tona dhe për të futur risi.',
            'Cili është shenja juaj zodiakale?': 'Kraba',
            'Cili është parfumi juaj i preferuar?': 'Aventus of Creed. Një përzierje sofistikuar që shpreh shijen e një jete të jetuar mirë.',
            'Cili është libri juaj i preferuar?': 'Meditimet, Marku Aureli.',
            'Qytete frymëzuese': 'Havana (Kuba), Siem Reap (Kamboxhia), Hanoi (Vietnam). Kulturat e paprekuara janë më tërheqëse për mua.',
          },
        },
      },
      'dr_firdavs_ahmedov': {
        'tr': {
          'biography': 'Dr. Firdavs Ahmedov, Smile Hair Clinic\'te Saç Ekimi Cerrahıdır. Ege Üniversitesi\'nden onur derecesi ile mezun oldu. Mount Sinai Hastanesi ve New York\'taki Askeri Hastanede eğitim aldı. 3500\'den fazla saç ekimi işlemini tamamladı.',
          'title': 'Saç Ekimi Cerrahı, M.D.',
          'specialization': 'Medikal Estetik Hekimi',
          'expertise': ['FUE', 'DHI', 'Revizyon Saç Ekimi', 'Safir Bıçaklar', 'Manuel ve Mikromotor'],
          'interview': {
            'Temel değerleriniz nelerdir?': 'Aidiyet duygusu yüksek bir ekiple çalışmaya ve aynı amaç için birlikte ilerlemeye değer veririm.',
            'Klinikte çalışma tarzınız nasıldır?': 'Bilgiye dayalı, farkındalığı yüksek, sürekli gelişimin sorumluluğunu üstlenen, dürüst profesyoneller ile çalışmak başarımızın temelidir.',
            'Burcunuz Nedir?': 'Aslan',
            'Favori Parfümünüz Hangisidir?': 'Dior Sauvage. Bu parfüm yüzleşmenin kokusudur. Her yeni gün içinizdeki vahşiyle uyanır ve onu bir beyefendiye dönüştürmeye çalışırsınız.',
            'Başucu kitabınız nedir?': 'Köpek Kalbi, Mihail Bulgakov. Hayat değiştiren operasyonlar yaptığımızı düşünürsek beni çok etkiliyor.',
            'İlham verici şehirler': 'New York, Boston, Seattle, İstanbul, Hong Kong ve Moskova. Ben gerçek bir dünya vatandaşıyım.',
          },
        },
        'en': {
          'biography': 'Dr. Firdavs Ahmedov is a Hair Transplant Surgeon at Smile Hair Clinic. He graduated with honors from Ege University. He received training at Mount Sinai Hospital and the Military Hospital in New York. He has completed over 3500 hair transplant procedures.',
          'title': 'Hair Transplant Surgeon, M.D.',
          'specialization': 'Medical Aesthetic Physician',
          'expertise': ['FUE', 'DHI', 'Revision Hair Transplant', 'Sapphire Blades', 'Manual and Micromotor'],
          'interview': {
            'What are your core values?': 'I value working with a team with a strong sense of belonging and moving forward together for the same purpose.',
            'How do you work at the clinic?': 'Working with knowledgeable, highly aware, honest professionals who take responsibility for continuous development is the foundation of our success.',
            'What is your zodiac sign?': 'Leo',
            'What is your favorite perfume?': 'Dior Sauvage. This perfume is the scent of confrontation. Every new day you wake up with the wild inside you and try to turn it into a gentleman.',
            'What is your bedside book?': 'Heart of a Dog, Mikhail Bulgakov. Considering that we perform life-changing operations, it affects me deeply.',
            'Inspiring cities': 'New York, Boston, Seattle, Istanbul, Hong Kong and Moscow. I am a true citizen of the world.',
          },
        },
        'ar': {
          'biography': 'الدكتور فيردافس أحمدوف هو جراح زراعة الشعر في عيادة سمايل هير. تخرج بامتياز من جامعة إيجة. تلقى تدريبًا في مستشفى جبل سinai والمستشفى العسكري في نيويورك. أكمل أكثر من 3500 إجراء لزراعة الشعر.',
          'title': 'جراح زراعة الشعر، دكتور في الطب',
          'specialization': 'طبيب التجميل الطبي',
          'expertise': ['FUE', 'DHI', 'زراعة الشعر المراجعة', 'شفرات الياقوت', 'اليدوية والميكروموتور'],
          'interview': {
            'ما هي قيمك الأساسية؟': 'أقدر العمل مع فريق يتمتع بإحساس قوي بالانتماء والتقدم معًا لنفس الهدف.',
            'كيف تعمل في العيادة؟': 'العمل مع محترفين على دراية عالية وواعين وصادقين يتحملون مسؤولية التطوير المستمر هو أساس نجاحنا.',
            'ما هو برجك؟': 'الأسد',
            'ما هو عطرك المفضل؟': 'Dior Sauvage. هذا العطر هو رائحة المواجهة. كل يوم جديد تستيقظ مع الوحش بداخلك وتحاول تحويله إلى رجل نبيل.',
            'ما هو كتابك المفضل؟': 'قلب الكلب، ميخائيل بولجاكوف. بالنظر إلى أننا نقوم بعمليات تغير الحياة، فإنه يؤثر علي بعمق.',
            'المدن الملهمة': 'نيويورك، بوسطن، سياتل، إسطنبول، هونغ كونغ وموسكو. أنا مواطن حقيقي في العالم.',
          },
        },
        'de': {
          'biography': 'Dr. Firdavs Ahmedov ist Haartransplantationschirurg bei Smile Hair Clinic. Er schloss sein Studium mit Auszeichnung an der Ege-Universität ab. Er erhielt eine Ausbildung am Mount Sinai Hospital und am Militärkrankenhaus in New York. Er hat über 3500 Haartransplantationsverfahren abgeschlossen.',
          'title': 'Haartransplantationschirurg, M.D.',
          'specialization': 'Medizinischer Ästhetiker',
          'expertise': ['FUE', 'DHI', 'Revision Haartransplantation', 'Saphir-Klingen', 'Manuell und Mikromotor'],
          'interview': {
            'Was sind Ihre Grundwerte?': 'Ich schätze die Arbeit mit einem Team mit starkem Zugehörigkeitsgefühl und das gemeinsame Vorankommen für denselben Zweck.',
            'Wie arbeiten Sie in der Klinik?': 'Die Arbeit mit sachkundigen, hochbewussten, ehrlichen Fachleuten, die Verantwortung für kontinuierliche Entwicklung übernehmen, ist die Grundlage unseres Erfolgs.',
            'Was ist Ihr Sternzeichen?': 'Löwe',
            'Was ist Ihr Lieblingsparfüm?': 'Dior Sauvage. Dieses Parfüm ist der Duft der Konfrontation. Jeden neuen Tag wachst du mit dem Wilden in dir auf und versuchst, es in einen Gentleman zu verwandeln.',
            'Was ist Ihr Lieblingsbuch?': 'Herz eines Hundes, Michail Bulgakow. Wenn man bedenkt, dass wir lebensverändernde Operationen durchführen, betrifft es mich zutiefst.',
            'Inspirierende Städte': 'New York, Boston, Seattle, Istanbul, Hongkong und Moskau. Ich bin ein wahrer Weltbürger.',
          },
        },
        'es': {
          'biography': 'El Dr. Firdavs Ahmedov es Cirujano de Trasplante de Cabello en Smile Hair Clinic. Se graduó con honores de la Universidad de Ege. Recibió capacitación en el Hospital Mount Sinai y el Hospital Militar en Nueva York. Ha completado más de 3500 procedimientos de trasplante de cabello.',
          'title': 'Cirujano de Trasplante de Cabello, M.D.',
          'specialization': 'Médico Estético',
          'expertise': ['FUE', 'DHI', 'Trasplante de Cabello de Revisión', 'Hojas de Zafiro', 'Manual y Micromotor'],
          'interview': {
            '¿Cuáles son sus valores fundamentales?': 'Valoro trabajar con un equipo con un fuerte sentido de pertenencia y avanzar juntos por el mismo propósito.',
            '¿Cómo trabaja en la clínica?': 'Trabajar con profesionales conocedores, altamente conscientes y honestos que asumen la responsabilidad del desarrollo continuo es la base de nuestro éxito.',
            '¿Cuál es su signo zodiacal?': 'Leo',
            '¿Cuál es su perfume favorito?': 'Dior Sauvage. Este perfume es el aroma de la confrontación. Cada nuevo día te despiertas con lo salvaje dentro de ti y tratas de convertirlo en un caballero.',
            '¿Cuál es su libro de cabecera?': 'Corazón de un Perro, Mijaíl Bulgákov. Considerando que realizamos operaciones que cambian la vida, me afecta profundamente.',
            'Ciudades inspiradoras': 'Nueva York, Boston, Seattle, Estambul, Hong Kong y Moscú. Soy un verdadero ciudadano del mundo.',
          },
        },
        'fr': {
          'biography': 'Le Dr Firdavs Ahmedov est chirurgien de greffe de cheveux à Smile Hair Clinic. Il est diplômé avec distinction de l\'Université d\'Ege. Il a reçu une formation au Mount Sinai Hospital et à l\'hôpital militaire de New York. Il a effectué plus de 3500 greffes de cheveux.',
          'title': 'Chirurgien de greffe de cheveux, M.D.',
          'specialization': 'Médecin esthétique',
          'expertise': ['FUE', 'DHI', 'Greffe de cheveux de révision', 'Lames de saphir', 'Manuel et micromoteur'],
          'interview': {
            'Quelles sont vos valeurs fondamentales?': 'Je valorise le travail avec une équipe ayant un fort sentiment d\'appartenance et avancer ensemble pour le même objectif.',
            'Comment travaillez-vous à la clinique?': 'Travailler avec des professionnels compétents, très conscients et honnêtes qui assument la responsabilité du développement continu est la base de notre succès.',
            'Quel est votre signe zodiacal?': 'Lion',
            'Quel est votre parfum préféré?': 'Dior Sauvage. Ce parfum est l\'odeur de la confrontation. Chaque nouveau jour, vous vous réveillez avec le sauvage en vous et essayez de le transformer en gentleman.',
            'Quel est votre livre de chevet?': 'Cœur d\'un chien, Mikhaïl Boulgakov. Considérant que nous effectuons des opérations qui changent la vie, cela m\'affecte profondément.',
            'Villes inspirantes': 'New York, Boston, Seattle, Istanbul, Hong Kong et Moscou. Je suis un vrai citoyen du monde.',
          },
        },
        'it': {
          'biography': 'Il Dott. Firdavs Ahmedov è Chirurgo del trapianto di capelli presso Smile Hair Clinic. Si è laureato con lode all\'Università di Ege. Ha ricevuto formazione presso il Mount Sinai Hospital e l\'Ospedale Militare di New York. Ha completato oltre 3500 procedure di trapianto di capelli.',
          'title': 'Chirurgo del trapianto di capelli, M.D.',
          'specialization': 'Medico estetico',
          'expertise': ['FUE', 'DHI', 'Trapianto di capelli di revisione', 'Lame di zaffiro', 'Manuale e micromotore'],
          'interview': {
            'Quali sono i tuoi valori fondamentali?': 'Apprezzo lavorare con un team con un forte senso di appartenenza e avanzare insieme per lo stesso scopo.',
            'Come lavori in clinica?': 'Lavorare con professionisti competenti, altamente consapevoli e onesti che assumono la responsabilità dello sviluppo continuo è la base del nostro successo.',
            'Qual è il tuo segno zodiacale?': 'Leone',
            'Qual è il tuo profumo preferito?': 'Dior Sauvage. Questo profumo è il profumo dello scontro. Ogni nuovo giorno ti svegli con il selvaggio dentro di te e cerchi di trasformarlo in un gentiluomo.',
            'Qual è il tuo libro preferito?': 'Cuore di un cane, Michail Bulgakov. Considerando che eseguiamo operazioni che cambiano la vita, mi colpisce profondamente.',
            'Città ispiratrici': 'New York, Boston, Seattle, Istanbul, Hong Kong e Mosca. Sono un vero cittadino del mondo.',
          },
        },
        'pt': {
          'biography': 'Dr. Firdavs Ahmedov é Cirurgião de Transplante de Cabelo na Smile Hair Clinic. Ele se formou com honras na Universidade de Ege. Recebeu treinamento no Mount Sinai Hospital e no Hospital Militar em Nova York. Ele completou mais de 3500 procedimentos de transplante de cabelo.',
          'title': 'Cirurgião de Transplante de Cabelo, M.D.',
          'specialization': 'Médico Estético',
          'expertise': ['FUE', 'DHI', 'Transplante de Cabelo de Revisão', 'Lâminas de Safira', 'Manual e Micromotor'],
          'interview': {
            'Quais são seus valores fundamentais?': 'Valorizo trabalhar com uma equipe com forte senso de pertencimento e avançar juntos para o mesmo propósito.',
            'Como você trabalha na clínica?': 'Trabalhar com profissionais conhecedores, altamente conscientes e honestos que assumem a responsabilidade pelo desenvolvimento contínuo é a base do nosso sucesso.',
            'Qual é seu signo?': 'Leão',
            'Qual é seu perfume favorito?': 'Dior Sauvage. Este perfume é o aroma do confronto. Todos os dias você acorda com o selvagem dentro de você e tenta transformá-lo em um cavalheiro.',
            'Qual é seu livro de cabeceira?': 'Coração de um Cão, Mikhail Bulgakov. Considerando que realizamos operações que mudam a vida, isso me afeta profundamente.',
            'Cidades inspiradoras': 'Nova York, Boston, Seattle, Istambul, Hong Kong e Moscou. Sou um verdadeiro cidadão do mundo.',
          },
        },
        'ru': {
          'biography': 'Доктор Фирдавс Ахмедов - хирург по пересадке волос в клинике Smile Hair. Он окончил с отличием Университет Эге. Он прошел обучение в больнице Маунт Синай и военной больнице в Нью-Йорке. Он выполнил более 3500 процедур пересадки волос.',
          'title': 'Хирург по пересадке волос, доктор медицины',
          'specialization': 'Врач-эстетик',
          'expertise': ['FUE', 'DHI', 'Ревизионная пересадка волос', 'Сапфировые лезвия', 'Ручной и микромотор'],
          'interview': {
            'Каковы ваши основные ценности?': 'Я ценю работу с командой с сильным чувством принадлежности и совместное продвижение к одной цели.',
            'Как вы работаете в клинике?': 'Работа с знающими, высоко осознанными, честными профессионалами, которые берут на себя ответственность за постоянное развитие, является основой нашего успеха.',
            'Какой у вас знак зодиака?': 'Лев',
            'Какой у вас любимый парфюм?': 'Dior Sauvage. Этот парфюм - аромат противостояния. Каждый новый день вы просыпаетесь с диким внутри себя и пытаетесь превратить его в джентльмена.',
            'Какая ваша любимая книга?': 'Собачье сердце, Михаил Булгаков. Учитывая, что мы выполняем операции, меняющие жизнь, это глубоко затрагивает меня.',
            'Вдохновляющие города': 'Нью-Йорк, Бостон, Сиэтл, Стамбул, Гонконг и Москва. Я настоящий гражданин мира.',
          },
        },
        'he': {
          'biography': 'ד"ר פירדאבס אחמדוב הוא מנתח השתלת שיער במרפאת סמייל היר. הוא סיים בהצטיינות מאוניברסיטת אגה. הוא קיבל הכשרה בבית החולים הר סיני ובבית החולים הצבאי בניו יורק. הוא השלים יותר מ-3500 הליכי השתלת שיער.',
          'title': 'מנתח השתלת שיער, ד"ר',
          'specialization': 'רופא אסתטי',
          'expertise': ['FUE', 'DHI', 'השתלת שיער תיקון', 'להבי ספיר', 'ידני ומיקרו-מוטור'],
          'interview': {
            'מהם הערכים הבסיסיים שלך?': 'אני מעריך עבודה עם צוות עם תחושת שייכות חזקה והתקדמות יחד לאותה מטרה.',
            'איך אתה עובד במרפאה?': 'עבודה עם אנשי מקצוע בעלי ידע, מודעות גבוהה וכנים הנוטלים אחריות על פיתוח מתמשך היא הבסיס להצלחתנו.',
            'מה המזל שלך?': 'אריה',
            'מה הבושם האהוב עליך?': 'Dior Sauvage. בושם זה הוא ריח העימות. כל יום חדש אתה מתעורר עם הפראי שבך ומנסה להפוך אותו לג\'נטלמן.',
            'מה הספר האהוב עליך?': 'לב כלב, מיכאיל בולגקוב. בהתחשב בכך שאנו מבצעים ניתוחים משני חיים, זה משפיע עלי עמוקות.',
            'ערים מעוררות השראה': 'ניו יורק, בוסטון, סיאטל, איסטנבול, הונג קונג ומוסקבה. אני אזרח אמיתי של העולם.',
          },
        },
        'sq': {
          'biography': 'Dr. Firdavs Ahmedov është Kirurg i Transplantimit të Flokëve në Smile Hair Clinic. Ai u diplomua me nder nga Universiteti i Ege. Ai mori trajnim në Spitalin Mount Sinai dhe Spitalin Ushtarak në New York. Ai ka përfunduar mbi 3500 procedura të transplantimit të flokëve.',
          'title': 'Kirurg i Transplantimit të Flokëve, M.D.',
          'specialization': 'Mjek Estetik',
          'expertise': ['FUE', 'DHI', 'Transplantimi i Flokëve i Rishikimit', 'Thikat Safir', 'Manual dhe Mikromotor'],
          'interview': {
            'Cilat janë vlerat tuaja themelore?': 'Vlerësoj punën me një ekip me ndjenjë të fortë të përkatësisë dhe të ecin përpara së bashku për të njëjtin qëllim.',
            'Si punoni në klinikë?': 'Puna me profesionistë të ditur, shumë të vetëdijshëm dhe të sinqertë që marrin përgjegjësi për zhvillimin e vazhdueshëm është themeli i suksesit tonë.',
            'Cili është shenja juaj zodiakale?': 'Luani',
            'Cili është parfumi juaj i preferuar?': 'Dior Sauvage. Ky parfum është aroma e konfrontimit. Çdo ditë e re ju zgjoheni me të egërnë brenda jush dhe përpiqeni ta shndërroni në një zotëri.',
            'Cili është libri juaj i preferuar?': 'Zemra e një qeni, Mikhail Bulgakov. Duke marrë parasysh që ne kryejmë operacione që ndryshojnë jetën, më prek thellësisht.',
            'Qytete frymëzuese': 'New York, Boston, Seattle, Istanbul, Hong Kong dhe Moskë. Jam një qytetar i vërtetë i botës.',
          },
        },
      },
      'dr_ali_osman_soluk': {
        'tr': {
          'biography': 'Dr. Ali Osman Soluk, İstanbul Tıp Fakültesi\'nden mezun oldu. İstanbul Büyükşehir Belediyesi\'nde üst düzey yönetici olarak görev yaptı. Hastane ve Sağlık Kurumları Yönetimi alanında yüksek lisans yaptı. Ozon tedavisi konusunda eğitim aldı.',
          'title': 'Saç Ekimi Cerrahı, M.D.',
          'specialization': 'Medikal Estetik Hekimi',
          'expertise': ['Saç Ekimi', 'Saç Tedavileri', 'Ozon Tedavisi', 'Medikal Estetik'],
          'interview': {
            'Temel değerleriniz nelerdir?': 'Yaptığım işte en iyi olmaya çalışmak. İşim ile ilgili güncel bilgilere sahip olmak için araştırmak.',
            'Klinikte çalışma tarzınız nasıldır?': 'Mükemmeli yakalamaya çalışmak. Hasta memnuniyetini ilk hedef olarak koymak.',
            'Burcunuz Nedir?': 'Aslan',
            'Favori Parfümünüz Hangisidir?': 'Kirke. Kokunun kalıcılığı ve notaları çok etkileyici.',
            'Başucu kitabınız nedir?': 'Da Vinci Şifresi. Tarihi yer tasvirleri ve anlatım stili çok başarılı. Yüzüklerin Efendisi ve Sherlock Holmes da sevdiğim kitaplardır.',
            'İlham verici şehirler': 'Barcelona ve Dubai. Birinin geçmiş ve günümüzü birleştirmesi, diğerinin çölden bir cazibe merkezi haline dönüşmesi beni etkiliyor.',
          },
        },
        'en': {
          'biography': 'Dr. Ali Osman Soluk graduated from Istanbul Medical Faculty. He served as a senior executive at Istanbul Metropolitan Municipality. He has a master\'s degree in Hospital and Health Institutions Management. He received training in ozone therapy.',
          'title': 'Hair Transplant Surgeon, M.D.',
          'specialization': 'Medical Aesthetic Physician',
          'expertise': ['Hair Transplant', 'Hair Treatments', 'Ozone Therapy', 'Medical Aesthetics'],
          'interview': {
            'What are your core values?': 'Trying to be the best at what I do. Researching to stay current with information related to my work.',
            'How do you work at the clinic?': 'Trying to achieve perfection. Making patient satisfaction the primary goal.',
            'What is your zodiac sign?': 'Leo',
            'What is your favorite perfume?': 'Circe. The persistence and notes of the scent are very impressive.',
            'What is your bedside book?': 'The Da Vinci Code. The historical place descriptions and narrative style are very successful. The Lord of the Rings and Sherlock Holmes are also books I love.',
            'Inspiring cities': 'Barcelona and Dubai. One combining the past and present, the other transforming from a desert into a center of attraction affects me.',
          },
        },
        'ar': {
          'biography': 'الدكتور علي عثمان سولوك تخرج من كلية الطب في إسطنبول. شغل منصب مدير تنفيذي في بلدية إسطنبول الكبرى. حصل على درجة الماجستير في إدارة المستشفيات والمؤسسات الصحية. تلقى تدريبًا في العلاج بالأوزون.',
          'title': 'جراح زراعة الشعر، دكتور في الطب',
          'specialization': 'طبيب التجميل الطبي',
          'expertise': ['زراعة الشعر', 'علاجات الشعر', 'العلاج بالأوزون', 'التجميل الطبي'],
          'interview': {
            'ما هي قيمك الأساسية؟': 'محاولة أن أكون الأفضل في ما أفعله. البحث للبقاء على اطلاع بالمعلومات المتعلقة بعملي.',
            'كيف تعمل في العيادة؟': 'محاولة تحقيق الكمال. جعل رضا المريض الهدف الأساسي.',
            'ما هو برجك؟': 'الأسد',
            'ما هو عطرك المفضل؟': 'Circe. استمرارية العطر ونوتاته مثيرة للإعجاب جدًا.',
            'ما هو كتابك المفضل؟': 'شفرة دافنشي. أوصاف الأماكن التاريخية وأسلوب السرد ناجحان جدًا. سيد الخواتم وشارلوك هولمز أيضًا من الكتب التي أحبها.',
            'المدن الملهمة': 'برشلونة ودبي. أحدها يجمع بين الماضي والحاضر، والآخر يتحول من صحراء إلى مركز جذب يؤثر علي.',
          },
        },
        'de': {
          'biography': 'Dr. Ali Osman Soluk absolvierte die medizinische Fakultät Istanbul. Er war leitender Angestellter bei der Istanbul Metropolitan Municipality. Er hat einen Master-Abschluss in Krankenhaus- und Gesundheitsinstitutionsmanagement. Er erhielt eine Ausbildung in Ozontherapie.',
          'title': 'Haartransplantationschirurg, M.D.',
          'specialization': 'Medizinischer Ästhetiker',
          'expertise': ['Haartransplantation', 'Haarbehandlungen', 'Ozontherapie', 'Medizinische Ästhetik'],
          'interview': {
            'Was sind Ihre Grundwerte?': 'Versuchen, in dem, was ich tue, der Beste zu sein. Recherchieren, um mit Informationen zu meiner Arbeit auf dem Laufenden zu bleiben.',
            'Wie arbeiten Sie in der Klinik?': 'Versuchen, Perfektion zu erreichen. Patientenzufriedenheit zum Hauptziel machen.',
            'Was ist Ihr Sternzeichen?': 'Löwe',
            'Was ist Ihr Lieblingsparfüm?': 'Circe. Die Beständigkeit und Noten des Duftes sind sehr beeindruckend.',
            'Was ist Ihr Lieblingsbuch?': 'Der Da Vinci Code. Die historischen Ortsbeschreibungen und der Erzählstil sind sehr erfolgreich. Der Herr der Ringe und Sherlock Holmes sind auch Bücher, die ich liebe.',
            'Inspirierende Städte': 'Barcelona und Dubai. Eine, die Vergangenheit und Gegenwart verbindet, die andere, die sich von einer Wüste zu einem Anziehungspunkt verwandelt, beeinflusst mich.',
          },
        },
        'es': {
          'biography': 'El Dr. Ali Osman Soluk se graduó de la Facultad de Medicina de Estambul. Se desempeñó como ejecutivo de alto nivel en el Municipio Metropolitano de Estambul. Tiene una maestría en Gestión de Hospitales e Instituciones de Salud. Recibió capacitación en terapia de ozono.',
          'title': 'Cirujano de Trasplante de Cabello, M.D.',
          'specialization': 'Médico Estético',
          'expertise': ['Trasplante de Cabello', 'Tratamientos Capilares', 'Terapia de Ozono', 'Estética Médica'],
          'interview': {
            '¿Cuáles son sus valores fundamentales?': 'Intentar ser el mejor en lo que hago. Investigar para mantenerme al día con información relacionada con mi trabajo.',
            '¿Cómo trabaja en la clínica?': 'Intentar lograr la perfección. Hacer de la satisfacción del paciente el objetivo principal.',
            '¿Cuál es su signo zodiacal?': 'Leo',
            '¿Cuál es su perfume favorito?': 'Circe. La persistencia y las notas del aroma son muy impresionantes.',
            '¿Cuál es su libro de cabecera?': 'El Código Da Vinci. Las descripciones de lugares históricos y el estilo narrativo son muy exitosos. El Señor de los Anillos y Sherlock Holmes también son libros que amo.',
            'Ciudades inspiradoras': 'Barcelona y Dubai. Una que combina el pasado y el presente, la otra transformándose de un desierto en un centro de atracción me afecta.',
          },
        },
        'fr': {
          'biography': 'Le Dr Ali Osman Soluk est diplômé de la Faculté de médecine d\'Istanbul. Il a servi comme cadre supérieur à la municipalité métropolitaine d\'Istanbul. Il a une maîtrise en gestion des hôpitaux et des institutions de santé. Il a reçu une formation en thérapie à l\'ozone.',
          'title': 'Chirurgien de greffe de cheveux, M.D.',
          'specialization': 'Médecin esthétique',
          'expertise': ['Greffe de cheveux', 'Traitements capillaires', 'Thérapie à l\'ozone', 'Esthétique médicale'],
          'interview': {
            'Quelles sont vos valeurs fondamentales?': 'Essayer d\'être le meilleur dans ce que je fais. Rechercher pour rester à jour avec les informations liées à mon travail.',
            'Comment travaillez-vous à la clinique?': 'Essayer d\'atteindre la perfection. Faire de la satisfaction du patient l\'objectif principal.',
            'Quel est votre signe zodiacal?': 'Lion',
            'Quel est votre parfum préféré?': 'Circe. La persistance et les notes du parfum sont très impressionnantes.',
            'Quel est votre livre de chevet?': 'Le Da Vinci Code. Les descriptions de lieux historiques et le style narratif sont très réussis. Le Seigneur des Anneaux et Sherlock Holmes sont aussi des livres que j\'aime.',
            'Villes inspirantes': 'Barcelone et Dubaï. L\'une combinant le passé et le présent, l\'autre se transformant d\'un désert en un centre d\'attraction m\'affecte.',
          },
        },
        'it': {
          'biography': 'Il Dott. Ali Osman Soluk si è laureato presso la Facoltà di Medicina di Istanbul. Ha servito come dirigente di alto livello presso il Comune Metropolitano di Istanbul. Ha un master in Gestione di Ospedali e Istituzioni Sanitarie. Ha ricevuto formazione in terapia con ozono.',
          'title': 'Chirurgo del trapianto di capelli, M.D.',
          'specialization': 'Medico estetico',
          'expertise': ['Trapianto di capelli', 'Trattamenti per capelli', 'Terapia con ozono', 'Estetica medica'],
          'interview': {
            'Quali sono i tuoi valori fondamentali?': 'Cercare di essere il migliore in quello che faccio. Ricercare per rimanere aggiornato con informazioni relative al mio lavoro.',
            'Come lavori in clinica?': 'Cercare di raggiungere la perfezione. Rendere la soddisfazione del paziente l\'obiettivo principale.',
            'Qual è il tuo segno zodiacale?': 'Leone',
            'Qual è il tuo profumo preferito?': 'Circe. La persistenza e le note del profumo sono molto impressionanti.',
            'Qual è il tuo libro preferito?': 'Il Codice Da Vinci. Le descrizioni dei luoghi storici e lo stile narrativo sono molto riusciti. Il Signore degli Anelli e Sherlock Holmes sono anche libri che amo.',
            'Città ispiratrici': 'Barcellona e Dubai. Una che combina passato e presente, l\'altra che si trasforma da un deserto in un centro di attrazione mi colpisce.',
          },
        },
        'pt': {
          'biography': 'Dr. Ali Osman Soluk formou-se na Faculdade de Medicina de Istambul. Serviu como executivo sênior na Prefeitura Metropolitana de Istambul. Tem mestrado em Gestão de Hospitais e Instituições de Saúde. Recebeu treinamento em terapia com ozônio.',
          'title': 'Cirurgião de Transplante de Cabelo, M.D.',
          'specialization': 'Médico Estético',
          'expertise': ['Transplante de Cabelo', 'Tratamentos Capilares', 'Terapia com Ozônio', 'Estética Médica'],
          'interview': {
            'Quais são seus valores fundamentais?': 'Tentar ser o melhor no que faço. Pesquisar para me manter atualizado com informações relacionadas ao meu trabalho.',
            'Como você trabalha na clínica?': 'Tentar alcançar a perfeição. Tornar a satisfação do paciente o objetivo principal.',
            'Qual é seu signo?': 'Leão',
            'Qual é seu perfume favorito?': 'Circe. A persistência e as notas do perfume são muito impressionantes.',
            'Qual é seu livro de cabeceira?': 'O Código Da Vinci. As descrições de lugares históricos e o estilo narrativo são muito bem-sucedidos. O Senhor dos Anéis e Sherlock Holmes também são livros que amo.',
            'Cidades inspiradoras': 'Barcelona e Dubai. Uma combinando passado e presente, a outra se transformando de um deserto em um centro de atração me afeta.',
          },
        },
        'ru': {
          'biography': 'Доктор Али Осман Солук окончил медицинский факультет Стамбула. Он работал старшим руководителем в муниципалитете Стамбула. У него есть степень магистра в области управления больницами и учреждениями здравоохранения. Он прошел обучение по озонотерапии.',
          'title': 'Хирург по пересадке волос, доктор медицины',
          'specialization': 'Врач-эстетик',
          'expertise': ['Пересадка волос', 'Лечение волос', 'Озонотерапия', 'Медицинская эстетика'],
          'interview': {
            'Каковы ваши основные ценности?': 'Пытаться быть лучшим в том, что я делаю. Исследовать, чтобы оставаться в курсе информации, связанной с моей работой.',
            'Как вы работаете в клинике?': 'Стремление к совершенству. Сделать удовлетворенность пациента основной целью.',
            'Какой у вас знак зодиака?': 'Лев',
            'Какой у вас любимый парфюм?': 'Circe. Стойкость и ноты аромата очень впечатляют.',
            'Какая ваша любимая книга?': 'Код да Винчи. Описания исторических мест и повествовательный стиль очень успешны. Властелин колец и Шерлок Холмс также книги, которые я люблю.',
            'Вдохновляющие города': 'Барселона и Дубай. Один, сочетающий прошлое и настоящее, другой, превращающийся из пустыни в центр притяжения, влияет на меня.',
          },
        },
        'he': {
          'biography': 'ד"ר עלי עוסמן סולוק סיים את הפקולטה לרפואה באיסטנבול. הוא שירת כמנהל בכיר בעיריית איסטנבול. יש לו תואר שני בניהול בתי חולים ומוסדות בריאות. הוא קיבל הכשרה בטיפול באוזון.',
          'title': 'מנתח השתלת שיער, ד"ר',
          'specialization': 'רופא אסתטי',
          'expertise': ['השתלת שיער', 'טיפולי שיער', 'טיפול באוזון', 'אסתטיקה רפואית'],
          'interview': {
            'מהם הערכים הבסיסיים שלך?': 'לנסות להיות הטוב ביותר במה שאני עושה. לחקור כדי להישאר מעודכן במידע הקשור לעבודה שלי.',
            'איך אתה עובד במרפאה?': 'לנסות להשיג שלמות. להפוך את שביעות הרצון של המטופל למטרה העיקרית.',
            'מה המזל שלך?': 'אריה',
            'מה הבושם האהוב עליך?': 'Circe. העמידות והנוטות של הבושם מרשימות מאוד.',
            'מה הספר האהוב עליך?': 'קוד דה וינצ\'י. התיאורים של מקומות היסטוריים וסגנון הסיפור מוצלחים מאוד. שר הטבעות ושרלוק הולמס הם גם ספרים שאני אוהב.',
            'ערים מעוררות השראה': 'ברצלונה ודובאי. אחת שמשלבת עבר והווה, השנייה שמשתנה ממדבר למרכז משיכה משפיעה עלי.',
          },
        },
        'sq': {
          'biography': 'Dr. Ali Osman Soluk u diplomua në Fakultetin e Mjekësisë në Istanbul. Ai shërbeu si ekzekutiv i lartë në Bashkinë Metropolitane të Istanbulit. Ai ka një master në Menaxhimin e Spitaleve dhe Institucioneve të Shëndetësisë. Ai mori trajnim në terapi me ozon.',
          'title': 'Kirurg i Transplantimit të Flokëve, M.D.',
          'specialization': 'Mjek Estetik',
          'expertise': ['Transplantimi i Flokëve', 'Trajtime të Flokëve', 'Terapia me Ozon', 'Estetika Mjekësore'],
          'interview': {
            'Cilat janë vlerat tuaja themelore?': 'Të përpiqem të jem më i miri në atë që bëj. Të kërkoj për të qëndruar i përditësuar me informacione që lidhen me punën time.',
            'Si punoni në klinikë?': 'Të përpiqem të arrij përsosmërinë. Të bëj kënaqësinë e pacientit objektivin kryesor.',
            'Cili është shenja juaj zodiakale?': 'Luani',
            'Cili është parfumi juaj i preferuar?': 'Circe. Qëndrueshmëria dhe notat e parfumit janë shumë mbresëlënëse.',
            'Cili është libri juaj i preferuar?': 'Kodi Da Vinci. Përshkrimet e vendeve historike dhe stili narrativ janë shumë të suksesshëm. Zoti i Unazave dhe Sherlock Holmes janë gjithashtu libra që i dua.',
            'Qytete frymëzuese': 'Barcelona dhe Dubai. Njëra që kombinon të kaluarën dhe të tashmen, tjetra që shndërrohet nga një shkretëtirë në një qendër tërheqjeje më prek.',
          },
        },
      },
      'dr_resat_arpaci': {
        'tr': {
          'biography': 'Dr. M. Reşat Arpacı, 2000 yılında Dokuz Eylül Üniversitesi\'nden mezun oldu. Milano Saç Ekimi Enstitüsü\'nden Biofibre Sertifikası aldı. 2007\'de gelişmiş FUE mikromotor tekniğini icat etti ve patentini aldı. 2010\'dan beri İstanbul\'da üst düzey kurumlarda görev yapıyor.',
          'title': 'Saç Ekimi Cerrahı, M.D.',
          'specialization': 'Medikal Estetik Hekimi',
          'expertise': ['FUE Mikromotor', 'Biofibre Sentetik Saç Ekimi', 'Saç Restorasyonu'],
          'interview': {
            'Temel değerleriniz nelerdir?': 'Temel prensibim adil olmaktır. Adaletin yaşamın temel felsefesi olduğunu düşünüyorum.',
            'Klinikte çalışma tarzınız nasıldır?': 'Ekibimdeki kişileri dinleyip onların fikirlerini değerlendirir, son kararı kendim vermeyi tercih ederim.',
            'Burcunuz Nedir?': 'Oğlak',
            'Favori Parfümünüz Hangisidir?': 'Sauvage. Kokusunu seviyorum.',
            'Başucu kitabınız nedir?': 'Homo Deus. İnsanın evriminin sonunda ortaya çıkan yarı tanrının yüksek egosu beni dehşete düşürüp hayran bırakmıştı.',
            'İlham verici şehirler': 'Barcelona, yaşanabilecek en güzel şehir. İstanbul ise tarihi dokusu ve kültürel çeşitliliğiyle yaşamayı sevdiğim şehir.',
          },
        },
        'en': {
          'biography': 'Dr. M. Reşat Arpacı graduated from Dokuz Eylül University in 2000. He received Biofibre Certification from the Milan Hair Transplant Institute. In 2007, he invented and patented the advanced FUE micromotor technique. He has been working at top institutions in Istanbul since 2010.',
          'title': 'Hair Transplant Surgeon, M.D.',
          'specialization': 'Medical Aesthetic Physician',
          'expertise': ['FUE Micromotor', 'Biofibre Synthetic Hair Transplant', 'Hair Restoration'],
          'interview': {
            'What are your core values?': 'My fundamental principle is to be fair. I think justice is the fundamental philosophy of life.',
            'How do you work at the clinic?': 'I listen to the people in my team, evaluate their ideas, and prefer to make the final decision myself.',
            'What is your zodiac sign?': 'Capricorn',
            'What is your favorite perfume?': 'Sauvage. I love its scent.',
            'What is your bedside book?': 'Homo Deus. The high ego of the demigod that emerged at the end of human evolution both terrified and amazed me.',
            'Inspiring cities': 'Barcelona, the most beautiful city to live in. Istanbul is the city I love to live in with its historical texture and cultural diversity.',
          },
        },
        'ar': {
          'biography': 'الدكتور م. رشاد أرجاجي تخرج من جامعة دوكوز إيلول في عام 2000. حصل على شهادة Biofibre من معهد ميلانو لزراعة الشعر. في عام 2007، اخترع وبراءة اختراع تقنية FUE الميكروموتور المتقدمة. يعمل في مؤسسات رائدة في إسطنبول منذ عام 2010.',
          'title': 'جراح زراعة الشعر، دكتور في الطب',
          'specialization': 'طبيب التجميل الطبي',
          'expertise': ['FUE الميكروموتور', 'زراعة الشعر الاصطناعي Biofibre', 'استعادة الشعر'],
          'interview': {
            'ما هي قيمك الأساسية؟': 'مبدأي الأساسي هو أن أكون عادلاً. أعتقد أن العدالة هي الفلسفة الأساسية للحياة.',
            'كيف تعمل في العيادة؟': 'أستمع إلى الأشخاص في فريقي، أقيم أفكارهم، وأفضل اتخاذ القرار النهائي بنفسي.',
            'ما هو برجك؟': 'الجدي',
            'ما هو عطرك المفضل؟': 'Sauvage. أحب رائحته.',
            'ما هو كتابك المفضل؟': 'Homo Deus. الأنا العالية للإله شبه الذي ظهر في نهاية التطور البشري أرهبتني وأذهلتني.',
            'المدن الملهمة': 'برشلونة، أجمل مدينة للعيش فيها. إسطنبول هي المدينة التي أحب العيش فيها مع نسيجها التاريخي وتنوعها الثقافي.',
          },
        },
        'de': {
          'biography': 'Dr. M. Reşat Arpacı absolvierte 2000 die Dokuz Eylül Universität. Er erhielt die Biofibre-Zertifizierung vom Mailänder Haartransplantationsinstitut. 2007 erfand und patentierte er die fortgeschrittene FUE-Mikromotor-Technik. Seit 2010 arbeitet er an führenden Institutionen in Istanbul.',
          'title': 'Haartransplantationschirurg, M.D.',
          'specialization': 'Medizinischer Ästhetiker',
          'expertise': ['FUE Mikromotor', 'Biofibre synthetische Haartransplantation', 'Haarrestaurierung'],
          'interview': {
            'Was sind Ihre Grundwerte?': 'Mein Grundprinzip ist es, fair zu sein. Ich denke, Gerechtigkeit ist die grundlegende Philosophie des Lebens.',
            'Wie arbeiten Sie in der Klinik?': 'Ich höre den Menschen in meinem Team zu, bewerte ihre Ideen und ziehe es vor, die endgültige Entscheidung selbst zu treffen.',
            'Was ist Ihr Sternzeichen?': 'Steinbock',
            'Was ist Ihr Lieblingsparfüm?': 'Sauvage. Ich liebe seinen Duft.',
            'Was ist Ihr Lieblingsbuch?': 'Homo Deus. Das hohe Ego des Halbgottes, der am Ende der menschlichen Evolution entstand, hat mich sowohl erschreckt als auch erstaunt.',
            'Inspirierende Städte': 'Barcelona, die schönste Stadt zum Leben. Istanbul ist die Stadt, in der ich gerne mit ihrer historischen Textur und kulturellen Vielfalt lebe.',
          },
        },
        'es': {
          'biography': 'El Dr. M. Reşat Arpacı se graduó de la Universidad Dokuz Eylül en 2000. Recibió la Certificación Biofibre del Instituto de Trasplante de Cabello de Milán. En 2007, inventó y patentó la técnica avanzada de micromotor FUE. Ha estado trabajando en instituciones líderes en Estambul desde 2010.',
          'title': 'Cirujano de Trasplante de Cabello, M.D.',
          'specialization': 'Médico Estético',
          'expertise': ['Micromotor FUE', 'Trasplante de Cabello Sintético Biofibre', 'Restauración Capilar'],
          'interview': {
            '¿Cuáles son sus valores fundamentales?': 'Mi principio fundamental es ser justo. Creo que la justicia es la filosofía fundamental de la vida.',
            '¿Cómo trabaja en la clínica?': 'Escucho a las personas en mi equipo, evalúo sus ideas y prefiero tomar la decisión final yo mismo.',
            '¿Cuál es su signo zodiacal?': 'Capricornio',
            '¿Cuál es su perfume favorito?': 'Sauvage. Me encanta su aroma.',
            '¿Cuál es su libro de cabecera?': 'Homo Deus. El alto ego del semidiós que surgió al final de la evolución humana me aterrorizó y me asombró.',
            'Ciudades inspiradoras': 'Barcelona, la ciudad más hermosa para vivir. Estambul es la ciudad en la que me encanta vivir con su textura histórica y diversidad cultural.',
          },
        },
        'fr': {
          'biography': 'Le Dr M. Reşat Arpacı est diplômé de l\'Université Dokuz Eylül en 2000. Il a reçu la certification Biofibre de l\'Institut de greffe de cheveux de Milan. En 2007, il a inventé et breveté la technique avancée de micromoteur FUE. Il travaille dans des institutions de premier plan à Istanbul depuis 2010.',
          'title': 'Chirurgien de greffe de cheveux, M.D.',
          'specialization': 'Médecin esthétique',
          'expertise': ['Micromoteur FUE', 'Greffe de cheveux synthétique Biofibre', 'Restauration capillaire'],
          'interview': {
            'Quelles sont vos valeurs fondamentales?': 'Mon principe fondamental est d\'être juste. Je pense que la justice est la philosophie fondamentale de la vie.',
            'Comment travaillez-vous à la clinique?': 'J\'écoute les personnes de mon équipe, j\'évalue leurs idées et je préfère prendre la décision finale moi-même.',
            'Quel est votre signe zodiacal?': 'Capricorne',
            'Quel est votre parfum préféré?': 'Sauvage. J\'aime son parfum.',
            'Quel est votre livre de chevet?': 'Homo Deus. Le haut ego du demi-dieu qui a émergé à la fin de l\'évolution humaine m\'a à la fois terrifié et émerveillé.',
            'Villes inspirantes': 'Barcelone, la plus belle ville où vivre. Istanbul est la ville où j\'aime vivre avec sa texture historique et sa diversité culturelle.',
          },
        },
        'it': {
          'biography': 'Il Dott. M. Reşat Arpacı si è laureato all\'Università Dokuz Eylül nel 2000. Ha ricevuto la Certificazione Biofibre dall\'Istituto di Trapianto di Capelli di Milano. Nel 2007, ha inventato e brevettato la tecnica avanzata del micromotore FUE. Lavora in istituzioni leader a Istanbul dal 2010.',
          'title': 'Chirurgo del trapianto di capelli, M.D.',
          'specialization': 'Medico estetico',
          'expertise': ['Micromotore FUE', 'Trapianto di capelli sintetico Biofibre', 'Restauro dei capelli'],
          'interview': {
            'Quali sono i tuoi valori fondamentali?': 'Il mio principio fondamentale è essere giusto. Penso che la giustizia sia la filosofia fondamentale della vita.',
            'Come lavori in clinica?': 'Ascolto le persone nel mio team, valuto le loro idee e preferisco prendere la decisione finale io stesso.',
            'Qual è il tuo segno zodiacale?': 'Capricorno',
            'Qual è il tuo profumo preferito?': 'Sauvage. Amo il suo profumo.',
            'Qual è il tuo libro preferito?': 'Homo Deus. L\'alto ego del semidio emerso alla fine dell\'evoluzione umana mi ha sia terrorizzato che stupito.',
            'Città ispiratrici': 'Barcellona, la città più bella dove vivere. Istanbul è la città in cui amo vivere con la sua texture storica e diversità culturale.',
          },
        },
        'pt': {
          'biography': 'Dr. M. Reşat Arpacı formou-se na Universidade Dokuz Eylül em 2000. Recebeu a Certificação Biofibre do Instituto de Transplante de Cabelo de Milão. Em 2007, inventou e patenteou a técnica avançada de micromotor FUE. Trabalha em instituições líderes em Istambul desde 2010.',
          'title': 'Cirurgião de Transplante de Cabelo, M.D.',
          'specialization': 'Médico Estético',
          'expertise': ['Micromotor FUE', 'Transplante de Cabelo Sintético Biofibre', 'Restauração Capilar'],
          'interview': {
            'Quais são seus valores fundamentais?': 'Meu princípio fundamental é ser justo. Acho que a justiça é a filosofia fundamental da vida.',
            'Como você trabalha na clínica?': 'Escuto as pessoas da minha equipe, avalio suas ideias e prefiro tomar a decisão final eu mesmo.',
            'Qual é seu signo?': 'Capricórnio',
            'Qual é seu perfume favorito?': 'Sauvage. Adoro seu perfume.',
            'Qual é seu livro de cabeceira?': 'Homo Deus. O alto ego do semideus que emergiu no final da evolução humana me aterrorizou e me surpreendeu.',
            'Cidades inspiradoras': 'Barcelona, a cidade mais bonita para viver. Istambul é a cidade em que amo viver com sua textura histórica e diversidade cultural.',
          },
        },
        'ru': {
          'biography': 'Доктор М. Решат Арпач окончил Университет Докуз Эйлюль в 2000 году. Он получил сертификат Biofibre от Миланского института пересадки волос. В 2007 году он изобрел и запатентовал передовую технику микромотора FUE. Он работает в ведущих учреждениях Стамбула с 2010 года.',
          'title': 'Хирург по пересадке волос, доктор медицины',
          'specialization': 'Врач-эстетик',
          'expertise': ['Микромотор FUE', 'Синтетическая пересадка волос Biofibre', 'Восстановление волос'],
          'interview': {
            'Каковы ваши основные ценности?': 'Мой фундаментальный принцип - быть справедливым. Я думаю, что справедливость - это фундаментальная философия жизни.',
            'Как вы работаете в клинике?': 'Я слушаю людей в моей команде, оцениваю их идеи и предпочитаю принимать окончательное решение сам.',
            'Какой у вас знак зодиака?': 'Козерог',
            'Какой у вас любимый парфюм?': 'Sauvage. Я люблю его аромат.',
            'Какая ваша любимая книга?': 'Homo Deus. Высокое эго полубога, появившегося в конце человеческой эволюции, одновременно ужаснуло и поразило меня.',
            'Вдохновляющие города': 'Барселона, самый красивый город для жизни. Стамбул - это город, в котором я люблю жить с его исторической текстурой и культурным разнообразием.',
          },
        },
        'he': {
          'biography': 'ד"ר מ. רשאט ארפאצ\'י סיים את אוניברסיטת דוקוז איילול בשנת 2000. הוא קיבל את אישור Biofibre ממכון השתלת השיער במילאנו. בשנת 2007, הוא המציא ופטנט את טכניקת המיקרו-מוטור FUE המתקדמת. הוא עובד במוסדות מובילים באיסטנבול מאז 2010.',
          'title': 'מנתח השתלת שיער, ד"ר',
          'specialization': 'רופא אסתטי',
          'expertise': ['מיקרו-מוטור FUE', 'השתלת שיער סינתטית Biofibre', 'שיקום שיער'],
          'interview': {
            'מהם הערכים הבסיסיים שלך?': 'העקרון הבסיסי שלי הוא להיות הוגן. אני חושב שצדק הוא הפילוסופיה הבסיסית של החיים.',
            'איך אתה עובד במרפאה?': 'אני מקשיב לאנשים בצוות שלי, מעריך את הרעיונות שלהם ומעדיף לקבל את ההחלטה הסופית בעצמי.',
            'מה המזל שלך?': 'גדי',
            'מה הבושם האהוב עליך?': 'Sauvage. אני אוהב את הריח שלו.',
            'מה הספר האהוב עליך?': 'Homo Deus. האגו הגבוה של האל למחצה שהופיע בסוף האבולוציה האנושית הפחיד אותי והדהים אותי.',
            'ערים מעוררות השראה': 'ברצלונה, העיר היפה ביותר לחיות בה. איסטנבול היא העיר שאני אוהב לחיות בה עם המרקם ההיסטורי והגיוון התרבותי שלה.',
          },
        },
        'sq': {
          'biography': 'Dr. M. Reşat Arpacı u diplomua në Universitetin Dokuz Eylül në vitin 2000. Ai mori Certifikatën Biofibre nga Instituti i Transplantimit të Flokëve në Milano. Në vitin 2007, ai shpiku dhe patentoi teknikën e avancuar të mikromotorit FUE. Ai ka punuar në institucione kryesuese në Istanbul që nga viti 2010.',
          'title': 'Kirurg i Transplantimit të Flokëve, M.D.',
          'specialization': 'Mjek Estetik',
          'expertise': ['Mikromotor FUE', 'Transplantimi i Flokëve Sintetik Biofibre', 'Rikthimi i Flokëve'],
          'interview': {
            'Cilat janë vlerat tuaja themelore?': 'Parimi im themelor është të jem i drejtë. Mendoj se drejtësia është filozofia themelore e jetës.',
            'Si punoni në klinikë?': 'Dëgjoj njerëzit në ekipin tim, vlerësoj idetë e tyre dhe preferoj të marr vendimin përfundimtar vetë.',
            'Cili është shenja juaj zodiakale?': 'Bricjapi',
            'Cili është parfumi juaj i preferuar?': 'Sauvage. E dua parfumin e tij.',
            'Cili është libri juaj i preferuar?': 'Homo Deus. Egoja e lartë e gjysmë-perëndisë që u shfaq në fund të evolucionit njerëzor më tmerroi dhe më mahniti.',
            'Qytete frymëzuese': 'Barcelona, qyteti më i bukur për të jetuar. Istanbul është qyteti në të cilin dua të jetoj me teksturën e tij historike dhe diversitetin kulturor.',
          },
        },
      },
      'dr_tarik_sarici': {
        'tr': {
          'biography': 'Dr. Tarık Sarıcı, saç ekimi ve saç restorasyonu alanında uzmanlaşmıştır.',
          'title': 'Saç Ekimi Cerrahı, M.D.',
          'specialization': 'Saç Ekimi ve Restorasyonu',
          'expertise': ['FUE', 'Sapphire FUE', 'Saç Çizgisi Tasarımı'],
          'interview': {
            'Motivasyonunuz nedir?': 'Hastalarımın özgüven kazanmasına katkı sağlamak.',
          },
        },
        'en': {
          'biography': 'Dr. Tarık Sarıcı specializes in hair transplant and hair restoration.',
          'title': 'Hair Transplant Surgeon, M.D.',
          'specialization': 'Hair Transplant and Restoration',
          'expertise': ['FUE', 'Sapphire FUE', 'Hairline Design'],
          'interview': {
            'What is your motivation?': 'To contribute to my patients gaining self-confidence.',
          },
        },
        'ar': {
          'biography': 'الدكتور طارق صاريجي متخصص في زراعة الشعر واستعادة الشعر.',
          'title': 'جراح زراعة الشعر، دكتور في الطب',
          'specialization': 'زراعة الشعر واستعادة الشعر',
          'expertise': ['FUE', 'زراعة الشعر FUE بالياقوت', 'تصميم خط الشعر'],
          'interview': {
            'ما هو دافعك؟': 'المساهمة في اكتساب مرضاي للثقة بالنفس.',
          },
        },
        'de': {
          'biography': 'Dr. Tarık Sarıcı ist spezialisiert auf Haartransplantation und Haarrekonstruktion.',
          'title': 'Haartransplantationschirurg, M.D.',
          'specialization': 'Haartransplantation und Rekonstruktion',
          'expertise': ['FUE', 'Saphir FUE', 'Haaransatz-Design'],
          'interview': {
            'Was ist Ihre Motivation?': 'Dazu beizutragen, dass meine Patienten Selbstvertrauen gewinnen.',
          },
        },
        'es': {
          'biography': 'El Dr. Tarık Sarıcı se especializa en trasplante de cabello y restauración capilar.',
          'title': 'Cirujano de Trasplante de Cabello, M.D.',
          'specialization': 'Trasplante de Cabello y Restauración',
          'expertise': ['FUE', 'Trasplante de Cabello FUE con Zafiro', 'Diseño de Línea de Cabello'],
          'interview': {
            '¿Cuál es su motivación?': 'Contribuir a que mis pacientes ganen confianza en sí mismos.',
          },
        },
        'fr': {
          'biography': 'Le Dr Tarık Sarıcı est spécialisé dans la greffe de cheveux et la restauration capillaire.',
          'title': 'Chirurgien de greffe de cheveux, M.D.',
          'specialization': 'Greffe de cheveux et restauration',
          'expertise': ['FUE', 'Greffe de cheveux FUE Saphir', 'Conception de la ligne de cheveux'],
          'interview': {
            'Quelle est votre motivation?': 'Contribuer à ce que mes patients gagnent en confiance en eux.',
          },
        },
        'it': {
          'biography': 'Il Dott. Tarık Sarıcı è specializzato in trapianto di capelli e restauro dei capelli.',
          'title': 'Chirurgo del trapianto di capelli, M.D.',
          'specialization': 'Trapianto di capelli e restauro',
          'expertise': ['FUE', 'Trapianto di capelli FUE Zaffiro', 'Progettazione della linea dei capelli'],
          'interview': {
            'Qual è la tua motivazione?': 'Contribuire a far guadagnare fiducia in se stessi ai miei pazienti.',
          },
        },
        'pt': {
          'biography': 'Dr. Tarık Sarıcı é especialista em transplante de cabelo e restauração capilar.',
          'title': 'Cirurgião de Transplante de Cabelo, M.D.',
          'specialization': 'Transplante de Cabelo e Restauração',
          'expertise': ['FUE', 'Transplante de Cabelo FUE Safira', 'Design da Linha do Cabelo'],
          'interview': {
            'Qual é sua motivação?': 'Contribuir para que meus pacientes ganhem autoconfiança.',
          },
        },
        'ru': {
          'biography': 'Доктор Тарык Сарыджи специализируется на пересадке волос и восстановлении волос.',
          'title': 'Хирург по пересадке волос, доктор медицины',
          'specialization': 'Пересадка волос и восстановление',
          'expertise': ['FUE', 'Пересадка волос FUE сапфиром', 'Дизайн линии волос'],
          'interview': {
            'Какая ваша мотивация?': 'Способствовать тому, чтобы мои пациенты обрели уверенность в себе.',
          },
        },
        'he': {
          'biography': 'ד"ר טאריק סאריצ\'י מתמחה בהשתלת שיער ושיקום שיער.',
          'title': 'מנתח השתלת שיער, ד"ר',
          'specialization': 'השתלת שיער ושיקום',
          'expertise': ['FUE', 'השתלת שיער FUE ספיר', 'עיצוב קו השיער'],
          'interview': {
            'מה המוטיבציה שלך?': 'לתרום לכך שמטופליי ירכושו ביטחון עצמי.',
          },
        },
        'sq': {
          'biography': 'Dr. Tarık Sarıcı është i specializuar në transplantimin e flokëve dhe rikthimin e flokëve.',
          'title': 'Kirurg i Transplantimit të Flokëve, M.D.',
          'specialization': 'Transplantimi i Flokëve dhe Rikthimi',
          'expertise': ['FUE', 'Transplantimi i Flokëve FUE Safir', 'Dizajni i Vijës së Flokëve'],
          'interview': {
            'Cila është motivimi juaj?': 'Të kontribuoj në fitimin e vetëbesimit të pacientëve të mi.',
          },
        },
      },
      'dr_atalare': {
        'tr': {
          'biography': 'Dr. Erhan Atalar, Smile Hair Clinic ekibine katılan yeni hekimlerimizden biridir. Saç sağlığı ve modern FUE tekniklerinde deneyimlidir.',
          'title': 'Saç Ekimi Cerrahı, M.D.',
          'specialization': 'Saç Ekimi ve Saç Sağlığı',
          'expertise': ['FUE', 'DHI', 'Saç Sağlığı Danışmanlığı'],
          'interview': {
            'Motivasyonunuz nedir?': 'Hastaların doğal görünümlerini yeniden kazanmalarına yardımcı olmak.',
          },
        },
        'en': {
          'biography': 'Dr. Erhan Atalar is one of our new doctors who joined the Smile Hair Clinic team. He is experienced in hair health and modern FUE techniques.',
          'title': 'Hair Transplant Surgeon, M.D.',
          'specialization': 'Hair Transplant and Hair Health',
          'expertise': ['FUE', 'DHI', 'Hair Health Consulting'],
          'interview': {
            'What is your motivation?': 'To help patients regain their natural appearance.',
          },
        },
        'ar': {
          'biography': 'الدكتور إرهان أتالار هو أحد أطبائنا الجدد الذين انضموا إلى فريق عيادة سمايل هير. لديه خبرة في صحة الشعر وتقنيات FUE الحديثة.',
          'title': 'جراح زراعة الشعر، دكتور في الطب',
          'specialization': 'زراعة الشعر وصحة الشعر',
          'expertise': ['FUE', 'DHI', 'استشارة صحة الشعر'],
          'interview': {
            'ما هو دافعك؟': 'مساعدة المرضى على استعادة مظهرهم الطبيعي.',
          },
        },
        'de': {
          'biography': 'Dr. Erhan Atalar ist einer unserer neuen Ärzte, die dem Smile Hair Clinic Team beigetreten sind. Er ist erfahren in Haargesundheit und modernen FUE-Techniken.',
          'title': 'Haartransplantationschirurg, M.D.',
          'specialization': 'Haartransplantation und Haargesundheit',
          'expertise': ['FUE', 'DHI', 'Haargesundheitsberatung'],
          'interview': {
            'Was ist Ihre Motivation?': 'Patienten helfen, ihr natürliches Aussehen wiederzuerlangen.',
          },
        },
        'es': {
          'biography': 'El Dr. Erhan Atalar es uno de nuestros nuevos médicos que se unió al equipo de Smile Hair Clinic. Tiene experiencia en salud capilar y técnicas modernas de FUE.',
          'title': 'Cirujano de Trasplante de Cabello, M.D.',
          'specialization': 'Trasplante de Cabello y Salud Capilar',
          'expertise': ['FUE', 'DHI', 'Consultoría de Salud Capilar'],
          'interview': {
            '¿Cuál es su motivación?': 'Ayudar a los pacientes a recuperar su apariencia natural.',
          },
        },
        'fr': {
          'biography': 'Le Dr Erhan Atalar est l\'un de nos nouveaux médecins qui a rejoint l\'équipe de Smile Hair Clinic. Il est expérimenté en santé capillaire et en techniques FUE modernes.',
          'title': 'Chirurgien de greffe de cheveux, M.D.',
          'specialization': 'Greffe de cheveux et santé capillaire',
          'expertise': ['FUE', 'DHI', 'Conseil en santé capillaire'],
          'interview': {
            'Quelle est votre motivation?': 'Aider les patients à retrouver leur apparence naturelle.',
          },
        },
        'it': {
          'biography': 'Il Dott. Erhan Atalar è uno dei nostri nuovi medici che si è unito al team di Smile Hair Clinic. Ha esperienza in salute dei capelli e tecniche moderne FUE.',
          'title': 'Chirurgo del trapianto di capelli, M.D.',
          'specialization': 'Trapianto di capelli e salute dei capelli',
          'expertise': ['FUE', 'DHI', 'Consulenza sulla salute dei capelli'],
          'interview': {
            'Qual è la tua motivazione?': 'Aiutare i pazienti a recuperare il loro aspetto naturale.',
          },
        },
        'pt': {
          'biography': 'Dr. Erhan Atalar é um dos nossos novos médicos que se juntou à equipe da Smile Hair Clinic. Ele tem experiência em saúde capilar e técnicas modernas de FUE.',
          'title': 'Cirurgião de Transplante de Cabelo, M.D.',
          'specialization': 'Transplante de Cabelo e Saúde Capilar',
          'expertise': ['FUE', 'DHI', 'Consultoria de Saúde Capilar'],
          'interview': {
            'Qual é sua motivação?': 'Ajudar os pacientes a recuperarem sua aparência natural.',
          },
        },
        'ru': {
          'biography': 'Доктор Эрхан Аталар - один из наших новых врачей, присоединившихся к команде клиники Smile Hair. Он имеет опыт в здоровье волос и современных техниках FUE.',
          'title': 'Хирург по пересадке волос, доктор медицины',
          'specialization': 'Пересадка волос и здоровье волос',
          'expertise': ['FUE', 'DHI', 'Консультация по здоровью волос'],
          'interview': {
            'Какая ваша мотивация?': 'Помочь пациентам восстановить их естественный внешний вид.',
          },
        },
        'he': {
          'biography': 'ד"ר ארהאן אטאלר הוא אחד מהרופאים החדשים שלנו שהצטרף לצוות מרפאת סמייל היר. יש לו ניסיון בבריאות שיער וטכניקות FUE מודרניות.',
          'title': 'מנתח השתלת שיער, ד"ר',
          'specialization': 'השתלת שיער ובריאות שיער',
          'expertise': ['FUE', 'DHI', 'ייעוץ בריאות שיער'],
          'interview': {
            'מה המוטיבציה שלך?': 'לעזור למטופלים להשיב את המראה הטבעי שלהם.',
          },
        },
        'sq': {
          'biography': 'Dr. Erhan Atalar është një nga mjekët tanë të rinj që u bashkua ekipit të Smile Hair Clinic. Ai ka përvojë në shëndetin e flokëve dhe teknikat moderne FUE.',
          'title': 'Kirurg i Transplantimit të Flokëve, M.D.',
          'specialization': 'Transplantimi i Flokëve dhe Shëndeti i Flokëve',
          'expertise': ['FUE', 'DHI', 'Konsultim Shëndeti i Flokëve'],
          'interview': {
            'Cila është motivimi juaj?': 'Të ndihmoj pacientët të rikthejnë pamjen e tyre natyrore.',
          },
        },
      },
      'dr_yusuf_gunel': {
        'tr': {
          'biography': 'Dr. Yusuf Günel, saç ekimi ve revizyon operasyonlarında deneyimlidir.',
          'title': 'Saç Ekimi Cerrahı, M.D.',
          'specialization': 'Saç Ekimi ve Revizyon Operasyonları',
          'expertise': ['DHI', 'FUE', 'Revizyon Saç Ekimi'],
          'interview': {
            'Motivasyonunuz nedir?': 'Doğal ve kalıcı sonuçlar elde etmek.',
          },
        },
        'en': {
          'biography': 'Dr. Yusuf Günel is experienced in hair transplant and revision operations.',
          'title': 'Hair Transplant Surgeon, M.D.',
          'specialization': 'Hair Transplant and Revision Operations',
          'expertise': ['DHI', 'FUE', 'Revision Hair Transplant'],
          'interview': {
            'What is your motivation?': 'To achieve natural and permanent results.',
          },
        },
        'ar': {
          'biography': 'الدكتور يوسف جونيل لديه خبرة في زراعة الشعر وعمليات المراجعة.',
          'title': 'جراح زراعة الشعر، دكتور في الطب',
          'specialization': 'زراعة الشعر وعمليات المراجعة',
          'expertise': ['DHI', 'FUE', 'زراعة الشعر المراجعة'],
          'interview': {
            'ما هو دافعك؟': 'تحقيق نتائج طبيعية ودائمة.',
          },
        },
        'de': {
          'biography': 'Dr. Yusuf Günel ist erfahren in Haartransplantation und Revisionsoperationen.',
          'title': 'Haartransplantationschirurg, M.D.',
          'specialization': 'Haartransplantation und Revisionsoperationen',
          'expertise': ['DHI', 'FUE', 'Revisions-Haartransplantation'],
          'interview': {
            'Was ist Ihre Motivation?': 'Natürliche und dauerhafte Ergebnisse zu erzielen.',
          },
        },
        'es': {
          'biography': 'El Dr. Yusuf Günel tiene experiencia en trasplante de cabello y operaciones de revisión.',
          'title': 'Cirujano de Trasplante de Cabello, M.D.',
          'specialization': 'Trasplante de Cabello y Operaciones de Revisión',
          'expertise': ['DHI', 'FUE', 'Trasplante de Cabello de Revisión'],
          'interview': {
            '¿Cuál es su motivación?': 'Lograr resultados naturales y permanentes.',
          },
        },
        'fr': {
          'biography': 'Le Dr Yusuf Günel est expérimenté en greffe de cheveux et opérations de révision.',
          'title': 'Chirurgien de greffe de cheveux, M.D.',
          'specialization': 'Greffe de cheveux et opérations de révision',
          'expertise': ['DHI', 'FUE', 'Greffe de cheveux de révision'],
          'interview': {
            'Quelle est votre motivation?': 'Obtenir des résultats naturels et permanents.',
          },
        },
        'it': {
          'biography': 'Il Dott. Yusuf Günel è esperto in trapianto di capelli e operazioni di revisione.',
          'title': 'Chirurgo del trapianto di capelli, M.D.',
          'specialization': 'Trapianto di capelli e operazioni di revisione',
          'expertise': ['DHI', 'FUE', 'Trapianto di capelli di revisione'],
          'interview': {
            'Qual è la tua motivazione?': 'Ottenere risultati naturali e permanenti.',
          },
        },
        'pt': {
          'biography': 'Dr. Yusuf Günel tem experiência em transplante de cabelo e operações de revisão.',
          'title': 'Cirurgião de Transplante de Cabelo, M.D.',
          'specialization': 'Transplante de Cabelo e Operações de Revisão',
          'expertise': ['DHI', 'FUE', 'Transplante de Cabelo de Revisão'],
          'interview': {
            'Qual é sua motivação?': 'Alcançar resultados naturais e permanentes.',
          },
        },
        'ru': {
          'biography': 'Доктор Юсуф Гюнель имеет опыт в пересадке волос и ревизионных операциях.',
          'title': 'Хирург по пересадке волос, доктор медицины',
          'specialization': 'Пересадка волос и ревизионные операции',
          'expertise': ['DHI', 'FUE', 'Ревизионная пересадка волос'],
          'interview': {
            'Какая ваша мотивация?': 'Достичь естественных и постоянных результатов.',
          },
        },
        'he': {
          'biography': 'ד"ר יוסוף גונל מנוסה בהשתלת שיער וניתוחי תיקון.',
          'title': 'מנתח השתלת שיער, ד"ר',
          'specialization': 'השתלת שיער וניתוחי תיקון',
          'expertise': ['DHI', 'FUE', 'השתלת שיער תיקון'],
          'interview': {
            'מה המוטיבציה שלך?': 'להשיג תוצאות טבעיות וקבועות.',
          },
        },
        'sq': {
          'biography': 'Dr. Yusuf Günel ka përvojë në transplantimin e flokëve dhe operacionet e rishikimit.',
          'title': 'Kirurg i Transplantimit të Flokëve, M.D.',
          'specialization': 'Transplantimi i Flokëve dhe Operacionet e Rishikimit',
          'expertise': ['DHI', 'FUE', 'Transplantimi i Flokëve i Rishikimit'],
          'interview': {
            'Cila është motivimi juaj?': 'Të arrij rezultate natyrore dhe të përhershme.',
          },
        },
      },
    };
  }
}

